### ISSUE TITLE
AV.Promise `then` 不总是异步执行的

### ISSUE THREAD

**Issue by jcppman** [leancloud/javascript-sdk#103]
Hi, 

版本为`0.5.3`, installed via bower

问题描述
------------

不同的时机`then`同一个promise, 执行的顺序不相同

Reproduce
--------------

```javascript

//构造一个会在200ms后resolve as 'hello'的promise
var a = new AV.Promise(function(resolve){
  setTimeout(function(){
    resolve('hello');
  }, 200);
});

//测试函数
function test(){
  console.log('before');
  a.then(function(val){
    console.log(val);
  });
  console.log('after');
}

test();  //结果如预期: 'before', 'after', 'hello'

setTimeout(function(){
  test(); //结果为'before', 'hello', 'after'
}, 1000);

```

问题
------

若无法确定该`then`为异步或同步执行，在某些应用场景下必须要自己主动`setTimeout(f, 0);`来避免问题 (比如在AngularJS下若在`then`里面使用`$apply`则会出错，因为已经在某个`$digest`内了)

其他符合Promise A+的库的行为如ES6 Promise, Q, when等，执行结果符合预期, `then`总是被异步执行

**Comment by killme2008** [comment]
我们将在今天发布后解决这个问题，感谢反馈。

**Comment by killme2008** [comment]
昨天已发布 v0.5.5
