### ISSUE TITLE
调研如何支持 blob 格式上传

### ISSUE THREAD

**Issue by wangxiao** [leancloud/javascript-sdk#112]
来自用户问题
https://ticket.leancloud.cn/tickets/7876

**Comment by Hybrid-Force** [comment]
Hi @wangxiao,

我之前对JS SDK做过一个修改，允许客户端[用blob来新建一个`AV.File`](https://github.com/Hybrid-Force/javascript-sdk/blob/master/lib/file.js#L332)。然后通过LeanCloud的内部API来获取七牛上传凭证，然后[直接上传到七牛](https://github.com/Hybrid-Force/javascript-sdk/blob/master/lib/file.js#L603)。我自己一直在用这个新加的API。

用法大概是这样：
```
// someBlob is some blob....
var newFile = new AV.File('filename', {blob: someBlob});
newFile.upload();
```


不知是否符合你的需要。如果有需要的话，我可以去重新整理一下发个PR。

**Comment by wangxiao** [comment]
@Hybrid-Force 跪谢。。。

**Comment by wennyyuan** [comment]
@Hybrid-Force Hi~非常感谢你的分享，如果方便的话，求微信联系方式~

**Comment by Hybrid-Force** [comment]
@wangxiao 我新建了一个branch，发了一个[PR](https://github.com/leancloud/javascript-sdk/pull/114)

**Comment by wennyyuan** [comment]
顺手回复我嘛~
