### ISSUE TITLE
node.js 环境替换 XMLHttpRequest

### ISSUE THREAD

**Issue by aisk** [leancloud/javascript-sdk#125]
目前有如下已知问题：

- [不支持 keep alive](https://github.com/leancloud/javascript-sdk/issues/117)
- [不支持 HTTP_PROXY 等环境变量](https://github.com/leancloud/javascript-sdk/issues/58)

但是具体使用哪个模块，我还没有想清楚，有如下几个选择：

- [browserify](https://github.com/request/request) 功能强大，但体积比较大，browserify 到浏览器可能会压力比较大。
- [fetch](https://github.com/github/fetch) 以后会是标准浏览器实现，但是貌似不支持上面两个需要的特性。

其他欢迎补充。

**Comment by wangxiao** [comment]
这个已经替换了吧？https://github.com/leancloud/javascript-sdk/pull/178
