### ISSUE TITLE
SDK 0.6.0 Unusable with React Native Packager

### ISSUE THREAD

**Issue by Hybrid-Force** [leancloud/javascript-sdk#134]
## Description
0.6.0版本兼容Browserify，利用package.json的`browser`配置可以在浏览器和Node环境中能各自加载适用于当前环境的模块。但是，在React Native环境中，JS SDK完全不能用了。

React Native的packager不检查package.json中的`browser`的配置选项，不能选择性的加载适用的模块。这导致React Native尝试加载错误的`xmlhttprequest`模块并出错且无法启动应用。

0.6.0版本的这个错误比之前的[AsyncStorage的问题](issue #115)更加严重，AsyncStorage的问题只是导致不能持久话session，而这个问题导致应用无法启动。

## Screenshot
![image](https://cloud.githubusercontent.com/assets/978994/9499308/59722a1c-4c51-11e5-99f0-8ac4523e6763.png)

**Comment by leeyeh** [comment]
>React Native的packager不检查package.json中的browser的配置选项

https://github.com/facebook/react-native/issues/10#issuecomment-91663040
https://github.com/facebook/react-native/pull/2208

FYI.

**Comment by Hybrid-Force** [comment]
哦，好像是react native packager的问题。packager的确检查了package.json的browser配置，但是对于形如`"xmlhttprequest": "./lib/browserify-wrapper/xmlhttprequest-browser.js"`这样的配置就不能处理了。

**Comment by leeyeh** [comment]
已在 0.10.0 中确认无法运行。

**Comment by Hybrid-Force** [comment]
我去开了一个React Native Packager的[bug](https://github.com/facebook/react-native/issues/2459)。

另外，React Native Packer不能解析path模块。

**Comment by leeyeh** [comment]
:+1:

**Comment by smalllixin** [comment]
@Hybrid-Force 目前有什么work around可以解决这个问题么？

**Comment by leeyeh** [comment]
@smalllixin 这个 issue 里提到的两个问题：

1. react-native 不完全支持 browser 字段导致 xmlhttprequest 未找到
2. react-native 不支持 path 模块

暂时的解决方法：

1. patch react-native with https://github.com/facebook/react-native/pull/2499.patch
2. 手动改 avoscloud-sdk
  - 删除 https://github.com/leancloud/javascript-sdk/blob/master/lib/file.js#L3
  - https://github.com/leancloud/javascript-sdk/blob/master/lib/file.js#L517 改为 `var extName = _self.name.match(/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/)[4];`

**Comment by Hybrid-Force** [comment]
@smalllixin 在react-native merge @leeyeh 同学的PR之前，我有一个[临时的branch](https://github.com/Hybrid-Force/javascript-sdk/tree/feature/react-native)暂时解决了上述的两个问题以及对 asyc storage的适配。

1. react-native 的packager不完全支持browser字段，所以不依赖于 browser字段，通过`lib/xmlhttpreqeust.js`模块来加载浏览器或者node module。
2. react-native 的packager不包含path模块的支持，因此手动添加`path` module的依赖。
3. 顺便加了个'lib/storage.js' 来适配react-native 的 `AsyncStorage`。增加了一个`AV.User.currentAsync` API。通过这样的方法来获取当前用户:
```
AV.User.currentAsync()
    .then(user => console.log(user));
```

另外， @leeyeh 同学发现react-native对[WebSocket的支持也有点问题](https://github.com/facebook/react-native/pull/2599)，估计JS IM SDK的使用会有影响。

**Comment by h3l** [comment]
![qq20151023-0 2x](https://cloud.githubusercontent.com/assets/1664952/10671743/ed3d8bf2-791e-11e5-875e-03b85d7e7ea7.png)
@Hybrid-Force 你好，我这边使用了你的临时branch后报了上图的错误，麻烦问下如何解决

**Comment by leeyeh** [comment]
@h3l 请升级到 avoscloud-sdk@1.0.0-rc2 试试。

**Comment by h3l** [comment]
@leeyeh 非常感谢，解决了，没想到npm install avoscloud-sdk —save默认安装的是0.6几版本的
