### ISSUE TITLE
Promise .then中的异常没有被抛出

### ISSUE THREAD

**Issue by tuoxiansp** [leancloud/javascript-sdk#144]
try{
            console.log('start');
            new Promise(function(fulfill, reject) {

            }).then(function() {
                undefined.get();
                console.log('success');
            });
        }
        catch(e) {
            console.log('failed');
            console.error(e);
        }
如这段代码，then捕获了异常。导致既不success也不failed
看了源码，then=try，不太科学，感觉

**Comment by leeyeh** [comment]
你是不想这样：
```javascript
console.log('start');
new Promise(function(fulfill, reject) {

}).then(function() {
  undefined.get();
  console.log('success');
}).catch(function(e) {
  console.log('failed');
  console.error(e);
});
```

**Comment by tuoxiansp** [comment]
不是。
可以这样看，把我上面代码的try catch去掉，变成这样
        console.log('start');
        new Promise(function(fulfill, reject) {

        }).then(function() {
            undefined.get();
            console.log('success');
        });

then方法中出现异常，但是debug工具中却打印不出异常，因为异常在then中被捕获了。
我理解的是then中出现异常是应该抛出的，而不是被像try一样被捕获。

**Comment by leeyeh** [comment]
`p.then(onFullfilled, onRejected)` 的 onFullfilled 与 onRejected 中抛出异常 e 时，p 应该被 rejected with e as the reasone。

**Comment by aisk** [comment]
可以试一下 ES6 里面的 Promise，也是同样的行为。

**Comment by tuoxiansp** [comment]
这里跟你们文档里推荐的Promise迷你书说的不一致
http://liubin.github.io/promises-book/#then-or-catch
我再去查查ES6的。

**Comment by leeyeh** [comment]
@tuoxiansp http://liubin.github.io/promises-book/#not-throw-use-reject

**Comment by leeyeh** [comment]
另 @wangxiao  @killme2008 @aisk 

目前的 chrome 已经能够在控制台中打印出 Promise 中抛出但是未捕获的异常了，但是应该只支持原生 Promise。我们能不能直接使用浏览器的实现，在不支持的情况下再退化为我们的 polyfill 呢。

**Comment by tuoxiansp** [comment]
我的理解有问题，还是不能跟着直觉走。
感谢指正。

**Comment by aisk** [comment]
@leeyeh 一直想做这件事来着的，但是目前 node.js 环境下，为了兼容以前用户的代码，已经默认把 Promise/A+ 兼容关闭了，和原生实现不兼容了。

@killme2008 @sdjcw 是否可以考虑找个时间推荐用户开启并且修改代码做兼容？

**Comment by leeyeh** [comment]
我们能不能给云代码增加 sdk 版本选择功能，然后不统一升级。以后 sdk 升级 API 都要向前兼容也不是个办法。

**Comment by aisk** [comment]
@leeyeh LeanEngine 3.0 需要用户在 package.json 里面指定 SDK 版本了，因此只要给出升级警告，应该没有问题。

LeanEngine 2.0 的项目可以考虑在 cloud-code 内部默认把 _isPromisesAPlusCompliant 关闭。想要开启的话推荐升级到 LeanEngine 3.0。 

@sdjcw

**Comment by sdjcw** [comment]
LeanEngine 2.0 现在依赖 js-sdk 0.6.1 版本，js-sdk 在 0.5.7 版本已经修改成 「AV.Promise 仅在非 node 环境（如浏览器）默认启用 PromiseA+ 兼容模式」，并且增加了一个调试选项，更多请看这里：https://github.com/leancloud/javascript-sdk/blob/master/changelog.md

**Comment by tuoxiansp** [comment]
谢谢，完美解决了我的问题。
