### ISSUE TITLE
Promise有问题

### ISSUE THREAD

**Issue by wmzy** [leancloud/javascript-sdk#146]
version：0.6.1
看图吧：

![_003](https://cloud.githubusercontent.com/assets/5526525/9812965/03e8b27c-58b4-11e5-9b5f-a946750630cb.png)
![_004](https://cloud.githubusercontent.com/assets/5526525/9812964/03e81b82-58b4-11e5-9e8f-18085cf0d680.png)

**Comment by leeyeh** [comment]
默认情况下，sdk 使用的 Promise 不是 Promise A+ 标准的实现，你可以通过 `Promise.setPromisesAPlusCompliant(true)` 来使其兼容 Promise A+ 标准。

**Comment by wmzy** [comment]
多谢，希望文档能详细些。单元测试总过不了，折磨了我大半天。。

**Comment by killme2008** [comment]
@wmzy 感谢你的建议，我们会增加下文档。
