### ISSUE TITLE
记住登录状态的问题,无法获得AV.User.current()

### ISSUE THREAD

**Issue by mqliutie** [leancloud/javascript-sdk#153]
```

var currentUser = AV.User.current();
if (currentUser) {
  // do stuff with the user
} else {
  // show the signup or login page
}

```

登录成功后 `currentUser = null`

**Comment by mqliutie** [comment]
好像登录成功后没有将信息保存到 `localStorage`

我输出了一下 `window.localStorage` 结果是下面这样的 : 

```

Storage {AV/Btbn4kpsQ7ChGnQBQQGKwJ56/installationId: "3325594d-7b28-f3c1-a4cf-ae0137c50485", debug: "undefined"}

```
文档中 : 

无论你使用任何注册或者登录方法，用户都会在 localStorage 中储存，你可以把缓存作为一个 session 对待，并且自动假设用户已经登录了。


文档说会在 `localStorage` 中存储

**Comment by killme2008** [comment]
如果是 null ，那肯定是没有登录成功，当然 localStorage 也没有值。

**Comment by mqliutie** [comment]
怎么判定成功? 我通过http get 请求 leancloud 验证已经通过了呀, 这不算登录成功么?

**Comment by mqliutie** [comment]
$http.get("https://leancloud.cn/1.1/login?username="+username+"&password="+password)

**Comment by killme2008** [comment]
这是通过 ajax 登录，跟 js sdk  毫无关系。他不会去保存 current user，道理不是很明显吗？只有通过 js sdk  登录，我们才会去帮你管理，否则都是你要自己管理。

**Comment by mqliutie** [comment]
哦 - -

**Comment by killme2008** [comment]
登录参考

https://leancloud.cn/docs/js_guide.html#登录

**Comment by wangxiao** [comment]
。。。确实，应该是没弄清楚 Angular 和 JS SDK 的关系。
