### ISSUE TITLE
使用react-native在ios模拟器下首次运行会报错

### ISSUE THREAD

**Issue by liiklin** [leancloud/javascript-sdk#161]
react-native demo在ios模拟器下首次运行会报错，如下图。
![image](https://cloud.githubusercontent.com/assets/7721623/10659269/24517fac-78d1-11e5-8ad0-2ecda914ad83.png)
再次点击就会add按钮会提示成功。
真机没有测试。

**Comment by leeyeh** [comment]
我更新一下 demo。

**Comment by leeyeh** [comment]
Fixed in v1.0.0-rc2.

**Comment by leeyeh** [comment]
Shipped with v1.0.0-rc3
