### ISSUE TITLE
realtime的JS源文件在storage之前引入，会导致AV.realtime undefined

### ISSUE THREAD

**Issue by nicecui** [leancloud/javascript-sdk#165]
在一个App中，先引入AV.realtime.js，再引入av-mini-0.6.1.js。
在App中调用AV.realtime.version，显示AV.realtime为undefined。

先引入av-mini-0.6.1.js，再引入AV.realtime.js则问题解决。

**Comment by wangxiao** [comment]
已在 https://github.com/leancloud/javascript-sdk/pull/173 修复。
