### ISSUE TITLE
在react native中使用avoscloud-sdk推送消息

### ISSUE THREAD

**Issue by h3l** [leancloud/javascript-sdk#176]
我是希望在react native开发的应用中提供推送服务，看到了
https://blog.leancloud.cn/3188/这篇文章。

按照上文中的例子使用存储部分OK了，可是推送部分一直没弄好。我想问下在react native中使用avoscloud-sdk推送消息这块有文档，或者相应的demo么？

**Comment by leeyeh** [comment]
有的，估计今天能放出来，但是只支持 iOS。

**Comment by h3l** [comment]
好的，谢谢了，不过好像现在还没放出来呢

**Comment by leeyeh** [comment]
https://github.com/leancloud/javascript-sdk-installation-plugin

**Comment by leeyeh** [comment]
Demo:

**Comment by leeyeh** [comment]
点错按钮了，如有问题请 reopen。
