### ISSUE TITLE
2.0 需求讨论与收集

### ISSUE THREAD

**Issue by wangxiao** [leancloud/javascript-sdk#183]
##### 目标 
* 2.0 不是完全的重写，而是一次调整与重构；
* 代码层面更清晰合理，更易于维护；
* 现有不理想的 API 暴露修改为更优方式；
* 1.x 版本仍然继续维护；

**Comment by wangxiao** [comment]
https://github.com/leancloud/javascript-sdk/issues/184

**Comment by aisk** [comment]
不建议在没有了解现在源码情况下贸然重构。

**Comment by leeyeh** [comment]
建议使用 milestone 管理需求

**Comment by wangxiao** [comment]
2.0 不是完全的重写，而是一次调整与重构，这个是一个长期的 issue，先收集需求。
如果要真正去做，一定会去完整的了解具体的问题和实现，而且 2.0 也会是一个渐进的过程。
> 不建议在没有了解现在源码情况下贸然重构。

**Comment by wangxiao** [comment]
label 看着比较简单，等真正打算搞再设置 milestone 吧，先提需求。
> 建议使用 milestone 管理需求

**Comment by aisk** [comment]
@wangxiao 如果是渐进式的话就不用考虑 2.0 了，现有问题开 issue 一个一个解决就好。我们现在的版本号是语义化的，除非有重大 API 不兼容才会升级主版本号。

**Comment by wangxiao** [comment]
2.0 很有必要，因为可能会动 API，底层编写方式也可能逐步修改（比如 Promise 替换为原生）
> @wangxiao 如果是渐进式的话就不用考虑 2.0 了，现有问题开 issue 一个一个解决就好。我们现在的版本号是语义化的，除非有重大 API 不兼容才会升级主版本号。

**Comment by aisk** [comment]
替换 Promise 实现应该不影响上层 API

**Comment by wangxiao** [comment]
对，如果确实都没动，一点 API 没改，我们真正发版时不一定非要是 2.0 。但是收集需求用 2.0 目的也是希望大家不要太有包袱。
>替换 Promise 实现应该不影响上层 API

**Comment by sdjcw** [comment]
如何支持 Node.js 环境不使用 domain 的情况下传递 currentUser？

**Comment by leeyeh** [comment]
如果支持多例，每个 request 都 fork 一个 AV 出来能行吗？

**Comment by jacktator** [comment]
求AV.Object的 json 实例

**Comment by wangxiao** [comment]
多实例是应该支持一下，我记录下。
> 如果支持多例，然后每个 request 都 fork 一个 AV 出来能行吗？

**Comment by leeyeh** [comment]
@jacktator https://leancloud.cn/api-docs/javascript/symbols/AV.Object.html#toJSON

**Comment by sunchanglong** [comment]
>
* 代码层面更清晰合理，更易于维护；
* 现有不理想的 API 暴露修改为更优方式；

这两个并不能作为初衷。因为不能确认改变后的就是更好的。

### 建议从业务层面触发，不一定是我们自己现在想到的问题，先总结下用户提的论坛，ticket 中的问题。

**Comment by wangxiao** [comment]
好的，会再收集一下。我们自己就是我们 SDK 的用户，其中的些许问题，一直都是了解的，先建个 issue 记录下。
> 建议从业务层面触发，不一定是我们自己现在想到的问题，先总结下用户提的论坛，ticket 中的问题。

**Comment by wangxiao** [comment]
1.0 时期做过一次用户 SDK 用户访谈，已经过去一年，有些时期可能变了，但是部分仍有借鉴意义，补充在此作为参考。[查看文档](https://docs.google.com/document/d/1-ZdLPmVbaC8BfHerQISDLKi5LF9f37e59P374X2jKgQ/edit)（内部文档，暂不公开）

**Comment by aisk** [comment]
@sdjcw 感觉还是需要通过 request 对象来传递登录用户

**Comment by leeyeh** [comment]
@aisk 如果 AV 能多例的化可以这样：
```
AV.Cloud.define('fun', (req, res, AV) => {});
```

**Comment by jysperm** [comment]
现在多次用同一个类名调用 AV.Object.extend 会去 extend 之前定义过的同名 Class, 这个行为（https://github.com/leancloud/javascript-sdk/blob/53ef3b7a21a0b2f2a2262ed55326dd8353cd04b4/lib/object.js#L1344）我觉得不是很理解，也是这个行为导致会 Maximum call stack size exceeded.

我觉得完全可以去掉这个行为，改成多次用同样的名字调用 AV.Object.extend 返回同样的对象。

**Comment by aisk** [comment]
@leeyeh 多实例好像是个不错的解决方案，并且也支持用户在同一个进程内使用多个 LeanCloud APP 了。

**Comment by jysperm** [comment]
还有一点就是希望能将 throw 字符串的地方改成 throw 一个 Error 对象，否则没办法打印调用栈，和一些 Promise 库配合使用的时候也会有问题。

**Comment by wangxiao** [comment]
第一次需求评审的[会议记录](https://docs.google.com/document/d/16fYXxSAfJt1iBlJpyXSuC8RtmUZKbFIuMYY561Bw6yA/edit#heading=h.sxepl8r9weoj)
