### ISSUE TITLE
使用原生 Promise 

### ISSUE THREAD

**Issue by wangxiao** [leancloud/javascript-sdk#185]
去掉现有兼容版本的 AV.promise，使用原生 Promise 对象。

**Comment by wangxiao** [comment]
关联到 2.0 需求 https://github.com/leancloud/javascript-sdk/issues/183

**Comment by jysperm** [comment]
补充一下：

>在一个 rejectd 的 Promise 上调用 then 并传递一个 rejectCallback, 即使 rejectCallback 没有抛出异常，也会返回一个 rejected 的 Promise, 这个行为和 Promises/A+ 不兼容啊 ...

这个问题导致无法将一个 rejected 的 Promise 链变回 resloved, 在错误处理上会造成很多麻烦。

比如这个帖子（https://forum.leancloud.cn/t/javascript-catch-debug/5625 ），如果和 Promises/A+ 兼容的话，只需要在 `query.find({success, error})` 后面补一个 `.catch` 就好了，但现在 find 的异常（即使在 error 回调里已经处理过了）也会被继续传递到后面的 catch 块里，导致无法区分 find 的异常和 success/error 里的异常。

**Comment by wangxiao** [comment]
讨论之后，决定选择一个 Promise 库，我们不再自己维护。

**Comment by wangxiao** [comment]
https://github.com/leancloud/javascript-sdk/issues/210
