### ISSUE TITLE
支持可扩展的节点选择

### ISSUE THREAD

**Issue by leeyeh** [leancloud/javascript-sdk#189]
See #188 #108

**Comment by wangxiao** [comment]
对，我非常同意 https://github.com/leancloud/javascript-sdk/issues/108 ，目前的初始化方式明显不是 JS 的方式。但是 https://github.com/leancloud/javascript-sdk/issues/188 暂时没法开展，还是等明确上传节点规则之后搞。

**Comment by leeyeh** [comment]
需要节点命名文档，类似 http://docs.aws.amazon.com/general/latest/gr/rande.html。 ping @jwfing

**Comment by wangxiao** [comment]
这个不急，后端先调研吧，然后估计是每个 SDK 都会调整一次的。

**Comment by aisk** [comment]
现在 Python SDK 是 `CN` 和 `US`，不过估计很快 `CN` 这个名字就会不适用了……
