### ISSUE TITLE
按照教程跑 Demo 直接报错

### ISSUE THREAD

**Issue by yujiangshui** [leancloud/javascript-sdk#195]
按照这篇文章 https://blog.leancloud.cn/3188/ 写个 DEMO。

引入 `var AV = require('avoscloud-sdk').AV;` 刷新会直接报错：

![image](https://cloud.githubusercontent.com/assets/2942913/11785742/28d0385e-a2be-11e5-9385-8f052e1d782e.png)

相关版本：

OS X EL Capitan 10.11.2 (15C50)
Node v4.0.0
React Native 0.16.0
Xcode Version 7.2 (7C68)
Avoscloud-sdk 0.6.7

**Comment by sdjcw** [comment]
麻烦 @leeyeh 看下。

**Comment by leeyeh** [comment]
avoscloud-sdk 1.0.0 开始支持 react native，目前请在安装时手动指定版本：

```
npm install avoscloud-sdk@^1.0.0-rc5 --save
```

具体请参考这篇博客：https://blog.leancloud.cn/3993/

**Comment by yujiangshui** [comment]
成功了，感谢 @sdjcw @leeyeh ，希望可以在文章上加下注释。

**Comment by zhongxia245** [comment]
npm install avoscloud-sdk@^1.0.0-rc5 --save 
目前最新版本 1.0.0-rc8 这个版本在 RN 下使用报错,找不到 https 和 http

"avoscloud-sdk": "1.0.0-rc5",
    "react": "^0.14.8",
    "react-native": "^0.24.1"
 
不过 1.0.0-rc5 是可以的

**Comment by leeyeh** [comment]
fixed in 1.0.0-rc9，暂未发布，try master.
zhongxia <notifications@github.com>于2016年4月30日 周六19:36写道：
