### ISSUE TITLE
AV.Object 有一个统一的获取元素方法

### ISSUE THREAD

**Issue by wangxiao** [leancloud/javascript-sdk#196]
目前获取元素的方法非常不一致，虽然逻辑上说的通（一部分是自定义属性，一部分是服务器设置的），但是用户使用成本会稍微高点，会觉得不一致。

类似的例子很多，比如 AV.File 的 url 不是 file.url 也不是 file.get('url'); 而是 file.url() 其实都是很不一致的 API 暴露。

还有 createdAt 不能通过 get('createdAt'); 等，
都会增加用户使用成本。

https://github.com/leancloud/javascript-sdk/issues/183

**Comment by jiyehuang** [comment]
+1
