### ISSUE TITLE
用1.0.0-rc5 集成 react-native

### ISSUE THREAD

**Issue by buhe** [leancloud/javascript-sdk#197]
debug 的时候请求可以发送出去
非debug xcode 报错

tid:com.facebook.React.JavaScript] 'Error: undefined undefined is not a constructor (evaluating \'new AV.XMLHttpRequest()\')'
2015-12-17 15:01:26.562 [info][tid:com.facebook.React.JavaScript] { [TypeError: undefined is not a constructor (evaluating 'new AV.XMLHttpRequest()')]
  line: 57214,
  column: 30,
  sourceURL: 'http://10.29.206.236:8081/index.ios.bundle?platform=ios&dev=true' }
2015-12-17 15:01:26.567 [info][tid:com.facebook.React.JavaScript] 'Error: undefined undefined is not a constructor (evaluating \'new AV.XMLHttpRequest()\')'
2015-12-17 15:01:26.570 [info][tid:com.facebook.React.JavaScript] { [TypeError: undefined is not a constructor (evaluating 'new AV.XMLHttpRequest()')]
  line: 57214,
  column: 30,
  sourceURL: 'http://10.29.206.236:8081/index.ios.bundle?platform=ios&dev=true' }

**Comment by buhe** [comment]
pullTurningStep(success, fail) {
    //var objectId = UserStore.user.objectId;
    var objectId = '566e652c60b25b0437222a51';
    var user = new AV.User();
    //user.id = objectId;
    user.id = objectId

    var query = new AV.Query(Profile);
    query.equalTo('user', user);
    query.find({
      success: function (results) {
        var result = {};
        for (var i = 0; i < results.length; i++) {
          var data = results[i];
          var type = data.get('type');
          var step = data.get('step');
          if (result[type]) {
            result[type].push(step);
          } else {
            result[type] = [];
            result[type].push(step);
          }
        }
        //merge
        success(result);
      },
      error: function (error) {
        console.log("Error: " + error.code + " " + error.message);
        fail(error);
      }
    });
  }

代码如上,在 store 里面调用的. store 是 reflux 创建的.  我错过了什么？ thanks

**Comment by buhe** [comment]
```
var AV = require('avoscloud-sdk');
AV.initialize('OQYNgj8ffRah8qaSqaQjSgil-gzGzoHsz', 'CH8e9IdQw3FjIqJ14p2kJee2');
//AV.Promise.setPromisesAPlusCompliant(true);

var CheckIn = AV.Object.extend("CheckIn");
var Profile = AV.Object.extend("Profile");
import UserStore from '../stores/UserStore';
import moment from 'moment';

class API {
}
```
这个class 用的es6 的方式

**Comment by leeyeh** [comment]
React Native 什么版本？

**Comment by buhe** [comment]
"react": "^0.14.3",
 "react-native": "^0.13.2",

**Comment by leeyeh** [comment]
根据你的代码片段，猜测是在运行 `pullTurningStep` 方法中的 `query.find` 时报错，但是同样的代码没有复现，请问能否提供完整可运行的代码来调试下呢。

**Comment by buhe** [comment]
好。 我一会传到 github 上去

**Comment by buhe** [comment]
其实 是这样的。 我这边基本所有的 rest 请求在非debug 情况下都会报错. 
你们推荐的 react-native 版本是什么呢？ 我可以试试看

**Comment by buhe** [comment]
我自己用 superagent 是没有类似问题的.

**Comment by leeyeh** [comment]
0.13 版本没啥问题，你能提供一个可以复现问题的最小完整代码吗，我好跑起来。

**Comment by buhe** [comment]
```
 API.pullTurningStep(function (data) {
      console.log('bg invoke api' + this.toString());
  
      this.data = data;
      this.trigger(this);
    }.bind(this), function (err) {
      console.log(err);
      this.trigger(this);
    });
```
上面这样写是没问题,
```
var self = this;
 API.pullTurningStep(function (data) {
      console.log('bg invoke api' + self.toString());
  
      self.data = data;
      self.trigger(this);
    }, function (err) {
      console.log(err);
      this.trigger(this);
    });
```
这样就不行了。 我没深究，我这样写肯定不如上面，因为写习惯了。一直这么写，没想到遇到坑了。
有空帮忙看看为啥传进去不行，谢谢。

**Comment by leeyeh** [comment]
这两段代码是不一样的啊，`self.trigger(this);` 里的 `this` 是不是应该是 `self`。
尽管如此我还是没明白这个与上面报的错有啥关系。

**Comment by buhe** [comment]
恩，那个我写错了。 真实代码是 self 的。 
不过我 带入了真实代码中，还是不行。 还是一直

2015-12-18 11:49:27.650 [info][tid:com.facebook.React.JavaScript] { [TypeError: undefined is not a constructor (evaluating 'new AV.XMLHttpRequest()')]
  line: 57209,
  column: 30,
  sourceURL: 'http://10.29.206.236:8081/index.ios.bundle?platform=ios&dev=true' }

**Comment by leeyeh** [comment]
请至少提供一个能运行起来代码我才好查原因。

**Comment by buhe** [comment]
跟es6 的语法有关。 找到原因了. 我用的 import API from './api';
直接改成了var API = require('./api');
就可以了。 

API 里面是 对  leancloud的API的调用. 
感谢跟进

**Comment by buhe** [comment]
@leeyeh  
```
var React = require('react-native');
var API = require('./api');
var {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    Navigator,
    } = React;



var xxx = React.createClass({
  getInitialState: function () {
    //ResumesActionCreators.fetchResumes();
    return {
      data:{},
    };
  },
  componentDidMount(){
    console.log('invoke action');
    //Action.fetchByType('pushUp');
    API.pullTurningStep(function (data) {
      this.setState({data:data});
    }.bind(this), function (err) {
      console.log(err);
      this.setState({data:{err:err}});
    }.bind(this));
  },
  render: function () {
    return (
        <View>

          <Text style={{flex:1}}>
            {JSON.stringify(this.state.data)}
          </Text>

        </View>
    );

  },
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('xxx', () => xxx);
```

**Comment by buhe** [comment]
```(api/index.js)
 pullTurningStep(success, fail) {
    //var objectId = UserStore.user.objectId;
    var objectId = '566e652c60b25b0437222a51';
    var user = new AV.User();
    //user.id = objectId;
    user.id = objectId

    var query = new AV.Query(Profile);
    query.equalTo('user', user);
    query.find({
      success: function (results) {
        var result = {};
        for (var i = 0; i < results.length; i++) {
          var data = results[i];
          var type = data.get('type');
          var step = data.get('step');
          if (result[type]) {
            result[type].push(step);
          } else {
            result[type] = [];
            result[type].push(step);
          }
        }
        //merge
        success(result);
      },
      error: function (error) {
        console.log("Error: " + error.code + " " + error.message);
        fail(error);
      }
    });
  }
```

**Comment by buhe** [comment]
总结下来，直接调用 SDK 的class 不能用 import 引用。
