### ISSUE TITLE
AV.Error 没有继承 JavaScript 的 Error

### ISSUE THREAD

**Issue by jysperm** [leancloud/javascript-sdk#203]
不是 Error 对象的话和一些库配合起来会有问题，在一些 Promise 库里面，如果 throw 了一个不是继承自 Error 的对象会直接报错，请问是否有什么特别的考虑？

**Comment by leeyeh** [comment]
我觉得没有，直接改了或者直接 throw Error 吧。

**Comment by aisk** [comment]
这个应该是历史遗留问题，之前有一小部分改成 throw Error 了。可以全部改。

**Comment by jysperm** [comment]
补充一下：

>希望能将 throw 字符串的地方改成 throw 一个 Error 对象，否则没办法打印调用栈，和一些 Promise 库配合使用的时候也会有问题。
