### ISSUE TITLE
内部 AV._request 修改传参方式为传入一个 Object 

### ISSUE THREAD

**Issue by wangxiao** [leancloud/javascript-sdk#204]
AV._request = function (route, className, objectId, method, dataObject, sessionToken) 

这种形式很不易扩展，而且可读性也不好。

**Comment by jysperm** [comment]
支持，凡是分不出主次、或者参数比较多的函数都应该改成 object

**Comment by nicholasxjy** [comment]
如果查询参数很多，比如containedIn数组很大，get请求url会超出限制。

**Comment by leeyeh** [comment]
fixed in v3.0.0
