### ISSUE TITLE
增加 TypeScript .tsd 文件

### ISSUE THREAD

**Issue by aisk** [leancloud/javascript-sdk#206]
方便使用 TypeScript 的用户。

**Comment by jacktator** [comment]
看到这个必须上来支持下！

**Comment by aisk** [comment]
具体日程目前并不能定下来。另外欢迎有兴趣的同学一块来完成这项任务～

**Comment by gucheen** [comment]
开发组可以先搭建整个 SDK 的骨架，有兴趣的同学再来补充各个模块内的定义文件，因为对于我们来说，对 SDK 的了解不够多，要写出完整的定义结构来，太过困难了

**Comment by aisk** [comment]
@gucheen 好的，这块我会尽快完成的。

**Comment by dreday966** [comment]
typings 可以搜到avocloud-sdk有人使用成功了吗

**Comment by leeyeh** [comment]
DefinitelyTyped/DefinitelyTyped#9147 has been merged. Close this issue.
