### ISSUE TITLE
支持 NW.js 和 Electron

### ISSUE THREAD

**Issue by jysperm** [leancloud/javascript-sdk#211]
今天有用户提到这个需求，理论上是可以直接支持的，可能会有少许的兼容问题。

NW.js 和 Electron 下都同时有 Chromium 和 Node.js 环境，这两种情况都需要测试一下。

**Comment by simongfxu** [comment]
目前还没有测试吗？

我用electron写了个[小工具](https://github.com/simongfxu/violet)，打算用你们的sdk。
我个人感觉应该问题不大，等我入坑吧 :smile_cat:

**Comment by jysperm** [comment]
欢迎 🎉

**Comment by simongfxu** [comment]
目前在Electron的renderer process使用，基本上就是纯Chrome，没有发现问题。
使用到的接口注册/登录/查询/批量更新插入等。
main process还没用到。
:+1:

**Comment by leeyeh** [comment]
Closing it for now. 如果有问题请为具体问题新开 issue。
