### ISSUE TITLE
在RN环境中支持 push notification

### ISSUE THREAD

**Issue by buhe** [leancloud/javascript-sdk#215]
现在react native 分支挺不错的，但是不支持设备相关的push。只有基于web-socket的push。
iOS RN本身就支持，国外用gcm也没问题，但是国内想使用 leancloud的Android push，好像还需要适配下。
like this: https://github.com/zo0r/react-native-push-notification

**Comment by leeyeh** [comment]
近期没有计划实现 Android SDK 推送部分的 React Native 包装。如果实现也会是独立与 js sdk 的另外一个 package。具体方法可参考：http://facebook.github.io/react-native/docs/native-modules-android.html#content

**Comment by buhe** [comment]
恩。这个估计难度不大。封装一下你们 Android push SDK 就可以了
