### ISSUE TITLE
getACL() not working

### ISSUE THREAD

**Issue by sigshen** [leancloud/javascript-sdk#216]
javascript sdk文件中, AV.Object 有提供 getACL() 函數調用,
但是實測結果總是回傳 undefined

**Comment by leeyeh** [comment]
目前，出于隐私考虑，客户端查询的结果是不包含 ACL 的。我们计划当在 node 环境中使用 master key 进行查询时返回 ACL。请问这样能满足你的需求吗？

**Comment by sigshen** [comment]
可以的, 謝謝
不好意思, 想想請問issue 你們有預計多久會完成嗎？

**Comment by wangxiao** [comment]
你好，我们的任务会按照整体的优先级及难易度去完成，暂时没有这个 issue 的具体计划。另外 SDK 是开源的，也欢迎贡献代码，和我们一起完善。

**Comment by sigshen** [comment]
Okay I see, Thanks

**Comment by sigshen** [comment]
這部分需要 server side的支援, 但是我找不到相對應的repo,
請問 leancloud server side的部分是否沒有開源？

**Comment by wangxiao** [comment]
恩，暂时没有开源，已经提给后端工程师这个 issue 了。

**Comment by leeyeh** [comment]
已在 [v2.2.0](https://github.com/leancloud/javascript-sdk/releases/tag/v2.2.0) 中引入 `Query#includeACL` 方法解决。
