### ISSUE TITLE
Relation target class 为 _FIle时的错误

### ISSUE THREAD

**Issue by soargon** [leancloud/javascript-sdk#217]
使用include 无效
get('files').query() 又会报错...什么鬼啊
![123123123123](https://cloud.githubusercontent.com/assets/775878/12700103/ec4571f2-c80f-11e5-9319-3d23672e9230.jpg)

**Comment by leeyeh** [comment]
请给出完整的代码与你想到达到的预期的效果。

从你的描述中我看到是在对一个 AV.Relation 的实例进行操作，但是 AV.Relation 并没有 get 方法。
