### ISSUE TITLE
appId、AppKey 等放到 http request 的 header 中。

### ISSUE THREAD

**Issue by wangxiao** [leancloud/javascript-sdk#221]

**Comment by sdjcw** [comment]
放到 body 里面是为了实现简单跨域。
如果放在 header 里，则需要多一个 options 请求。

**Comment by wangxiao** [comment]
这样跨域好奇怪，而且不符合规则，也不符合我们自己给出的 REST API 啊。
options 请求仅请求服务器返回准许跨域的 response header，对服务器压力很大吗？

**Comment by sdjcw** [comment]
options 请求对服务器的压力我不确认。
我支持新版使用标准方式访问，服务端在尽量长的时间保持对老方式的支持。
这样可以保证新版本的请求可以很方便的被记录访问情况，方便问题排查。

**Comment by sdjcw** [comment]
@killme2008

**Comment by wangxiao** [comment]
我测了下，目前肯定是支持新版的 header（短的那种）的，我会在这个 issue 内一并支持。

**Comment by killme2008** [comment]
原来  parse 这么设计可能是考虑到效率问题，想避免一次 option 请求，如果觉的没有必要，我觉的可以统一掉。

**Comment by paomian** [comment]
我之前看过这一块，并不是所有请求都需要做跨域 option 请求，有个时间的限制，一次 option 请求之后的一段时间内，都不需要在做 option 请求了

**Comment by sdjcw** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS

服务器端可以响应 `Access-Control-Max-Age: 1728000` 这样的 header 给浏览器做参考，设置 7 天或者 10 天应该就差不多了。效率上应该问题不大。

**Comment by wangxiao** [comment]
好的，感谢。服务端请先调整下吧。

**Comment by killme2008** [comment]
服务端本来就有设置的。

**Comment by leeyeh** [comment]
node 的 ajax 实现还是旧的。
