### ISSUE TITLE
react-native是否可以使用统计sdk？

### ISSUE THREAD

**Issue by Richard-Cao** [leancloud/javascript-sdk#224]

**Comment by leeyeh** [comment]
暂时不支持

**Comment by Richard-Cao** [comment]
@leeyeh 会有支持的计划和打算吗

**Comment by leeyeh** [comment]
近期没有计划。

主要的问题是 js-analytics-sdk 目前有很多基于浏览器的概念是 React Native 中没有的，比如自动统计页面相关功能统计的维度是 window.location，需要监听 window 的 hashchange 事件。

**Comment by leeyeh** [comment]
FYI: https://github.com/leancloud/js-analytics-sdk
