### ISSUE TITLE
dist 中的文件命名问题

### ISSUE THREAD

**Issue by leeyeh** [leancloud/javascript-sdk#230]
之前我在很多地方用了 https://rawgit.com/leancloud/javascript-sdk/master/dist/av.js 现在这个文件没有了。建议 dist/av-es5.js 改名为 dist/av.js。
另外，一般 uglify 之后的文件命名是 min.js 而不是 mini 吧。

**Comment by wangxiao** [comment]
已修正，并重新构建。https://github.com/leancloud/javascript-sdk/pull/231

**Comment by leeyeh** [comment]
不要手动 close 没有 merge 的 issue，关联之后，merge RP 会自动 close 相关 issue。
