### ISSUE TITLE
这个是 NodeJS，不是 JavaScript

### ISSUE THREAD

**Issue by dotku** [leancloud/javascript-sdk#233]
有没有 JavaScript 前端版本的案例呀--？

**Comment by leeyeh** [comment]
JavaScript SDK 同时支持浏览器与 node 运行环境，请参考 [安装指南](https://leancloud.cn/docs/sdk_setup-js.html)

**Comment by leeyeh** [comment]
GitHub issues 仅接受 bug 反馈与 feature request，如有其他问题欢迎在我们的 [论坛](https://forum.leancloud.cn) 发帖讨论。谢谢支持。
