### ISSUE TITLE
100多k实在太大了，能否考虑为浏览器版本减小一下文件大小

### ISSUE THREAD

**Issue by Poordeveloper** [leancloud/javascript-sdk#243]
里面很多东西都用不上，我试图gulp release的时候去掉
file，relation之类的，文件稍微减小了一点，可是貌似关联性很强，会报错。既然你们到处都写着情怀，能否用点情怀在这上面。

**Comment by stonexer** [comment]
100k 还好吧，也没啥功能可以精简了。

**Comment by wangxiao** [comment]
我也觉得还好的大小，可以参考 jQuery 是 90kb 左右，angular 100 多 kb。
而且这个涉及到内部实现的问题，目前还没办法模块独立定制化。
