### ISSUE TITLE
fetch({ include: xxx }) 方法无效

### ISSUE THREAD

**Issue by nicecui** [leancloud/javascript-sdk#244]
#### 问题详情
https://forum.leancloud.cn/t/javascript-sdk-object-fetch/4506/6
用户报 fetch 的 then 和success 结果不一致。
@leeyeh 分析结果如下：
```
fetch 的 api 是 .fetch([fetchOptions,] callbacks)
因为最初的设计要支持 fetch({ success: {} )) 这样的用法，所以fetch({ include: xxx }) 是无效的，如果写成 .fetch(null, { include: xxx }) 也是可以的
我们之后应该会往 promise 靠渐渐废弃掉 callback 的用法，不过得看下怎么做
```

**Comment by guolin** [comment]
fetch(null, {include:xx}) 也是无效的。

我测试只有  fetch({include:xx}, {success: function(result){...}}) 可以用。

到底应该怎么用，希望问那个能够明确一下。

**Comment by leeyeh** [comment]
抱歉，写错了，应该是 `fetch({ include: xxx }, null)`
demo: http://jsplay.avosapps.com/jeg/edit?js,console

**Comment by leeyeh** [comment]
fixed in v2.0
