### ISSUE TITLE
Node SDK disableCurrentUser 相关需求

### ISSUE THREAD

**Issue by jysperm** [leancloud/javascript-sdk#251]
* [ ] disableCurrentUser 相关的警告只在启动时打印一次，以免日志打印过多；并用 console.trace() 打印调用栈，方便找到调用处。
* [x] 在 AV._config 中添加一个 userAgent 的配置，`browserify-wrapper/ajax.js` 按照这个选项来发 User Agent, 因为 Node SDK 方面有自定义 User Agent 用于服务器端统计的需求；之前和 @wangxiao 讨论过这个问题，现在 ajax-browser.js 和 ajax.js 的抽象层级并不一致，前者依赖 AV 对象而后者不依赖，这里需要考虑一下如何进行重构。
* [x] AV.Cloud.rpc 方法也需支持 sessionToken 参数，之前是因为 PR 合并顺序的缘故落下了这个函数。
* [x] disableCurrentUser 的情况下，AV.User.logOut 应该返回一个空的 Promise 而不是 `return console.warn();`

**Comment by wangxiao** [comment]
已经解决？

**Comment by jysperm** [comment]
「disableCurrentUser 相关的警告只在启动时打印一次」最后决定不做，其他都已完成，关闭掉。
