### ISSUE TITLE
为所有网络请求添加 useMasterKey 选项，允许在特定操作中使用 masterKey

### ISSUE THREAD

**Issue by jysperm** [leancloud/javascript-sdk#256]
如果在云引擎中用了 AV.Cloud.useMasterKey() 的话，无论设不设 sessionToken，都总是在以 masterKey 权限执行操作。这样的话可能存在安全隐患，我是希望能够默认不开 masterKey，但可以以 masterKey 的权限来发部分操作（在所有会发起网络请求的操作上加一个 useMasterKey 选项，和新增的 sessionToken 平级）。

**Comment by jysperm** [comment]
https://forum.leancloud.cn/t/leancloud/10519/5?u=jysperm

@sdjcw ：我觉得应该取消 “云引擎默认 masterKey 权限” 这个建议
@jysperm ：感觉这个的前提是 JS SDK 可以对单个请求指定使用或不使用 masterKey

**Comment by leeyeh** [comment]
#367
