### ISSUE TITLE
入门文档中，AV介绍没有require引用例子代码，不容易上手

### ISSUE THREAD

**Issue by idisblueflash** [leancloud/javascript-sdk#267]
比如我就得猜一下，这么写 `var AV = require('avoscloud-sdk');` 对不对。

https://leancloud.cn/docs/js_guide.html#AV_Object

**Comment by jysperm** [comment]
见安装指南 https://leancloud.cn/docs/sdk_setup-js.html
具体用什么名字引用取决于你使用的包管理器，在 NPM 下目前是 `avoscloud-sdk`

**Comment by idisblueflash** [comment]
建议在初始化的代码前加上AV的require，新用户会更明白怎么用：

```
var AV = require('javascript-idk');
//参数依次为 AppId, AppKey
AV.initialize('xxx-xx', 'xxx');
```

**Comment by jysperm** [comment]
主要是 JS SDK 可以通过很多种方式被加载，在不同的包管理器也可能有不同的名字，所以关于安装和加载的说明我们单独写在了「安装指南 https://leancloud.cn/docs/sdk_setup-js.html」这个页面。

**Comment by idisblueflash** [comment]
原谅我的较真：安装指南里没有 `var AV = require('avoscloud-sdk'); ` ，虽然能摸索出来，但是站在指南的角度，要是能补上这句，就会让后来人省力不少。

ps：你上面的链接“「安装指南 https://leancloud.cn/docs/sdk_setup-js.html」这个页面。” 没链接对。

**Comment by jysperm** [comment]
@leeyeh 是否需要在安装指南里补充一下通过每种方式安装后，在代码中的加载方式？不过我不确定这么做有多大意义，因为 JavaScript 的构建工具水好深的样子 ...

**Comment by leeyeh** [comment]
我觉得写出来没有什么坏处，目前构建工具支持的比较广泛的模块标准主要有 CommonJS，ES6 module 以及 AMD。我们只需要指出在这些标准下要如何引入，不需要详细到某种构建工具。

**Comment by wangxiao** [comment]
在快速入门中是有的。https://leancloud.cn/docs/start.html
![image](https://cloud.githubusercontent.com/assets/558368/18194721/4a6e0ace-711a-11e6-8df3-2624b61e3dd1.png)
