### ISSUE TITLE
react native 报错找不到模块

### ISSUE THREAD

**Issue by musicode** [leancloud/javascript-sdk#268]
![image](https://cloud.githubusercontent.com/assets/2732303/15066808/b61bb3fe-139e-11e6-81a6-edf558e06a9e.png)

这里用到了 node 的 http 模块，我理解在 RN 环境里找不到吧？

请问有什么解决办法么？

**Comment by leeyeh** [comment]
Dup of #253, please try master.

**Comment by liuyongjian** [comment]
照你说的试了，还找不到http模块

**Comment by leeyeh** [comment]
@liuyongjian 请先安装使用 1.0.0-rc7 或者 master。

**Comment by liuyongjian** [comment]
@leeyeh 我是在win7下开发的Android应用，rc7也找不到http，只有rc5可以。还有realtime实时聊天也老是显示超时，不能用。
