### ISSUE TITLE
[API missing]AV.Object.fetchAll

### ISSUE THREAD

**Issue by wujun4code** [leancloud/javascript-sdk#277]
## 含义
传入 AV.Object 数组，理论上它们各自都只有一个有效的 objectId，然后调用 AV.Object.fetchAll 可以把它们从服务端全部拉取到本地，实例代码如下：

```js
    AV.Object.fetchAll(avObjectArray).then(function (avobjs) {
    }, function (error) {
    });
```
iOS,Android 都有这个接口。

**Comment by nicecui** [comment]
https://forum.leancloud.cn/t/av-object-fetchall-is-not-a-function-javascript-fetchall/9398
加油快上

**Comment by nicecui** [comment]
https://forum.leancloud.cn/t/av-object-fetchall-is-not-a-function-javascript-fetchall/9398
