### ISSUE TITLE
react-native 请求报错

### ISSUE THREAD

**Issue by brightWeen** [leancloud/javascript-sdk#322]
环境是react-native,在android虚拟机里面跑的。
``` javascript
 var self  =this;
   var query = new AV.Query('MyUser');
    query.get('5773e5e2a633bd0057f4780a').then(function (data) {
    this.setState({userName:data.get("UserName")});
      // 成功获得实例
      // data 就是 id 为 57328ca079bc44005c2472d0 的 Todo 对象实例
    }, function (error) {
      // 失败了
    });
```

![image](https://cloud.githubusercontent.com/assets/1567099/16515789/a42980a2-3fa6-11e6-9a7c-a6ac9abab3f3.png)

**Comment by leeyeh** [comment]
请问 React Native 的版本是多少？

**Comment by brightWeen** [comment]
react-native-cli: 0.1.10
react-native: 0.24.1
leancloud-storage:1.2.1

**Comment by leeyeh** [comment]
confirmd, 请暂时使用 leancloud-storage@1.1

**Comment by brightWeen** [comment]
```
AV._config.APIServerURL = "https://api.leancloud.cn";  
```
最后调试发现没有APIServerURL， 加上这一句代码就可以了

**Comment by leeyeh** [comment]
请问你配置了正确的 appid 了吗，调试之后发现在 appid 不正确的情况下会出现 APIServerURL 没有设置的问题。

当然手动设置也能解决问题。

**Comment by brightWeen** [comment]
appid设置正确了，同样的代码在ios环境没有问题呢。

**Comment by leeyeh** [comment]
fixed in v1.3.0
