### ISSUE TITLE
最新的 leancloud-realtime 依赖的 avoscloud-sdk 版本是多少？

### ISSUE THREAD

**Issue by musicode** [leancloud/javascript-sdk#326]
javascript-sdk 的最新 release 版本是 1.2.1，但是在 npm 发布的版本是 1.0.0-rc9.2

在实际使用中，貌似只用到了：

```javascript
import AV from 'avoscloud-sdk'
```

我想知道是否需要更新到最新的 avoscloud-sdk，以及如何更新？

**Comment by leeyeh** [comment]
avoscloud-sdk is renamed to leancloud-storage since 1.0.0
