### ISSUE TITLE
「云引擎」 - 「在线编辑函数」中使用 AV.Object.extend 会造成 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nicecui** [leancloud/javascript-sdk#331]
问题来源：
https://forum.leancloud.cn/t/im/9851

问题详情：
如果有用户在 Hook 函数中使用了 AV.Object.extend 会出现 Maximum call stack size exceeded。
那么如何在「在线编辑函数」的 Hook 函数中对其他表进行「增加数据」的操作呢？

**Comment by jysperm** [comment]
https://github.com/leancloud/javascript-sdk/issues/183#issuecomment-159485657
去掉这个行为吧

**Comment by leeyeh** [comment]
每次 extend 都返回同一个类（而不是创建一个新的）如何

**Comment by jysperm** [comment]
我觉得可以直接去掉和 AV.Object._classMap 有关的代码，不去记录之前的类，每次 extend 返回一个新的类。

**Comment by leeyeh** [comment]
我想做这个的同时，支持 `class Test extends AV.Object {}` 的写法。这意味着：

- SDK 不再维护 `AV.Object._classMap`
- 移除 `AV.Object._getSubclass`，`AV.Object._create`，不再支持 `new AV.Object("ClassName")` 的用法
- 移除 `AV.Object#extend`

**Comment by jysperm** [comment]
「不再支持 new AV.Object("ClassName")」和「移除 AV.Object#extend」会不会有兼容的问题，我觉得可以继续保持兼容呀。

**Comment by leeyeh** [comment]
如果要支持，那就得维护 `AV.Object._classMap`

**Comment by jysperm** [comment]
`new AV.Object("ClassName")` 可以每次都返回一个空的类（而不是上一次构造的同名类），extend 同样每次返回新的类。

**Comment by jysperm** [comment]
虽然行为有变化，但我相信依赖这个行为的用户，和依赖 extend 的用户比起来还是少数。大部分用户都不会往类上面加方法。

**Comment by leeyeh** [comment]
我觉得没有人会用 `AV.Object#extend` 吧（不是 `AV.Object.extend`）。

**Comment by jysperm** [comment]
好吧，我理解错了。关于 `new AV.Object("ClassName")` 的话，本来我是想每次创建一个新的类，返回这个新的类的实例。但仔细想了一下这样也有坑（行为有变化、在循环里这样用会耗费额外的内存），所以不支持也好。

**Comment by sdjcw** [comment]
是否能淡化 AV.Object.extend 这个方法的使用，让普通用户在不需要额外实例方法时直接使用 new AV.Object('ClassName')，这个方法如果 ClassName 一样貌似是直接返回之前创建的对象的。

然后还保持 AV.Object.extend 现在的行为，创建新的 Class，但是注名副作用，提示在有必要的时候（比如要添加实例方法）才使用。

**Comment by leeyeh** [comment]
还是有问题，Query 的结果中可能会出现其他类，这样的话还是需要 `AV.Object._classMap`，这种情况下也不能为每个结果都创建一个类。

**Comment by sdjcw** [comment]
我希望你们给我科普下这个 AV.Object._classMap 存在的意义。

**Comment by leeyeh** [comment]
为了实现「单例」，也就是在我知道 className 的情况下，能够拿到这个 Class 的引用。

**Comment by wangxiao** [comment]
> 支持 class Test extends AV.Object {} 的写法

不使用 class 的写法是怎样的？

**Comment by leeyeh** [comment]
Parse 的做法是，第二次调用 `AV.Object.extend` 抛异常。🤔

**Comment by leeyeh** [comment]
`AV.Object._classMap` 中只保存 `AV.Object` 直接子类（`Animal`）。`new AV.Object('Animal')` 将实例化这个类。

`AV.Object.extend('Animal')` 每次都返回一个 `Animal` 类的子类，比如：`Duck = AV.Object.extend('Animal')`，而不是之前的 `Animal = AV.Object.extend('Animal')`。

针对 ES6 继承构造的 Class，提供 `AV.Object.registerSubClass` 方法将其添加到 _classMap

其他与现在保持不变。

**Comment by wangxiao** [comment]
SDK 层面最好就留一种写法，别给用户两种选择了。
既然是生成实例，建议保留 `const cat007 = new AV.Object('Cat');` 去掉 `AV.Object.extend()`。

**Comment by wangxiao** [comment]
不过，可以同时支持 class 的写法，毕竟语义会好些，但是感觉没有 `onst cat007 = new AV.Object('Cat');` 简单。

**Comment by jysperm** [comment]
「AV.Object.extend('Animal') 每次都返回一个 Animal 类的子类」这样不是还会有 Maximum call stack size exceeded 的问题么

**Comment by leeyeh** [comment]
不会啊，每次都创建了一个新的类

**Comment by jysperm** [comment]
新的类不会存储到 AV.Object._classMap 里？只有第一次 AV.Object.extend('Animal') 才会存到 classMap？

另外「AV.Object.extend('Animal') 每次都返回一个 Animal 类的子类」那么新的子类的名字在哪里指定？

**Comment by leeyeh** [comment]
第一次 AV.Object.extend('Animal') 会生成一个 Animal 类存到 AV.Object._classMap，然后返回一个 Animal 的子类。

子类的对应的还是 Animal 表，这个类的名字只是个本地的概念。

**Comment by jysperm** [comment]
这样概念有点复杂啊，完全可以不允许再定义子类。

**Comment by leeyeh** [comment]
>不允许再定义子类

那样的话，AV.Object.extend('Animal') 返回 Animal 类，第二次调用抛异常？覆盖 AV.Object._classMap？

**Comment by leeyeh** [comment]
总结一下现有的几个方案，目标是避免 Maximum call stack size exceeded：

#### 方案 1
调用`Animal = AV.Object.extend('Animal')` 时，子类的 constructor 不调用父类的 constructor。

Pros: 简单有效，改动最小
Cons: 继承是不完整的，可能会坑用户

#### 方案 2
第一次调用`Animal = AV.Object.extend('Animal', protoMembers, staticMembers)` 时生成一个直接继承自 AV.Object 的 Animal 类添加到 _classMap，对应 Animal 表，然后用 protoMembers, staticMembers 构造一个 Animal 类的子类返回。后面再调用则不再重新生成 Animal 类。

Cons: 与 Backbone 的概念不一致。从 JSON 构造的 Animal 实例将没有 protoMembers 与 staticMembers。循环中调用时，内存中可能存在多个类。

#### 方案 3
每次调用`Animal = AV.Object.extend('Animal', protoMembers, staticMembers)` 时都生成一个直接继承自 AV.Object 的 Animal 类添加/覆盖 _classMap.Animal。

Cons: 从 JSON 构造的 Animal 实例将使用最新定义的 Animal 类。循环中调用时，内存中可能存在多个类。

#### 方案 4
多次调用 `Animal = AV.Object.extend('Animal')` 时抛异常

Cons: 在线编辑函数时无法避免多次调用。

**Comment by jysperm** [comment]
我支持方案 3

**Comment by aisk** [comment]
方案三种每次调用 extend 都生成一个继承自现有类的新类，这样多次调用应该会导致内存占用一直增长的吧？

**Comment by jysperm** [comment]
如果没有引用的话会被 GC 的

**Comment by wangxiao** [comment]
这样可以么？

- 原来的接口完全保留，但 AV.Object.extend 方法多次调用给出错误 warning 非 throw error；
- 后续建议使用 `const cat007 = new AV.Object('Cat');` 方法直接生成实例，不是子类，子类不再缓存；

这样老的用户影响不会很大，新用户直接用 new AV.Object 就可以。

**Comment by leeyeh** [comment]
第一是在线编辑函数时无法避免多次调用。
第二是，`new AV.Object('Cat')` 内部调用了 `new Cat()`，还是需要缓存 Cat 类的。

**Comment by sdjcw** [comment]
即使是现在的实现，要避免在线定义函数多次调用 extend 也是可以的，只要写在 global 作用域就好了。

**Comment by leeyeh** [comment]
@sdjcw 先不论把定义与使用分开会是个多大的坑，我都想不到可以这么做何况用户。

**Comment by wangxiao** [comment]
补个背景：用户使用 AV.Object.extend 声明 Class 时，内部每次都会完整继承上次已经创建的同名 Class，包括相应的构造函数及 prototype 上的所有方法，并且会存储在 AV.Object._classMap 中。所以多次 extend 之后，之前声明过的同名 Class 永远不被 GC，最终导致内存溢出。

和 @leeyeh 讨论了一下，
打算采取上面的方案一，就是在调用 AV.Object.extend 时，不再完整的继承之前已经声明过的同名 Class，而是声明一个新的 Class，但是会将之前的同名 Class 中有差异的 prototype 上的方法（可能是用户自定义扩展的方法），挂载到新的 Class 上面，之后用新的 Class 覆盖原有同名的 Class，存储在 _classMap 中。

评估后，觉得这个方案改动最小，兼容性最强。

**Comment by leeyeh** [comment]
王潇与我都偏好方案 1，想听听其他人的想法。

**Comment by jysperm** [comment]
我依然偏好方案 2，因为我觉得这是一个理解起来最简单的方案，因为「extend 时会基于上一次 extend 的结果」本来就是一个比较奇怪的文档。

的确有兼容问题，但我相信多次调用 extend 的用户应该很少会添加自定义的方法。

>所以多次 extend 之后，之前声明过的同名 Class 永远不被 GC，最终导致内存溢出。

这个错误的根本原因是调用 constructor 导致的调用栈溢出，其实方案 1 也就是只改了这一点，但我觉得又增加了一个「不调用父类 constructor」会让行为更加复杂化（比如 AVObject 的 constructor 肯定是要调用的，最终子类的 constructor 也要调用，但中间的 constructor 却不调用）。

**Comment by aisk** [comment]
能不能只在第一次调用 extend 的时候创建类，后续一直都返回这个实例？

**Comment by leeyeh** [comment]
@asik consider:
```
var Test;
Test = AV.Object.extend('Test');
Test = AV.Object.extend('Test', {
   foo: () {};
});
new Test().foo();
```

**Comment by aisk** [comment]
@leeyeh 我觉得可以让用户避免出现这种情况。

**Comment by leeyeh** [comment]
我想到一个更简单的方案，保持现有的机制，当不带第二个参数调用 `AV.Object.extend('Test')` 时，直接返回当前的 _classMap 中的 Test 类。

**Comment by asik** [comment]
Lol @aisk everytime someone mistypes your name they summon me instead :P
