### ISSUE TITLE
[React-Native]ERROR!!!

### ISSUE THREAD

**Issue by Richard-Cao** [leancloud/javascript-sdk#354]
react-native upgrade to 0.32.0, leancloud-storage report error.
<img width="543" alt="559113c5-76c5-4d90-9d6e-9cdb4a35f4a1" src="https://cloud.githubusercontent.com/assets/5953992/18014191/58dacc58-6bf4-11e6-9df5-b03375f35eb3.png">

https://github.com/leancloud/javascript-sdk/blob/master/src/browserify-wrapper/localstorage-browser.js#L53

How to solve?????

**Comment by leeyeh** [comment]
Fixed in v1.4.0-beta.0

**Comment by BinaryHB** [comment]
详见：https://forum.leancloud.cn/t/js-sdk-react-native-require/10574
