### ISSUE TITLE
AV.File对象调用save方法，saveOptions设置onprogress回调方法，并没有执行

### ISSUE THREAD

**Issue by 2016geek** [leancloud/javascript-sdk#355]
handleUpload(target){
        let img = target.target.files[0];
        let imged =new AV.File(img.name,img);
        imged.save({
            onprogress:function(){console.log('test');}
        }).then((data)=>this.setState({imgurl:data.attributes.url}));
    }
图片保存成功了，但是onprogress回调函数没有执行。我的目的其实就是想显示图片上传进度，请问有什么好的解决方法吗？

**Comment by leeyeh** [comment]
很抱歉，目前的 API 中，save 方法有两个参数，saveOptions 与 callbacks，如果只有一个参数时会认为是 callbacks。所以需要写成：

```
file.save({
  onprogress: xxx,
}, {}).then(...)
```

为了保持向前兼容，我们不会在当前的版本中修改这个行为。

**Comment by 2016geek** [comment]
@leeyeh 我刚才试了一下，在后面又加了一个回调，但是前面onprogress函数在图片上传的时候没有执行，回调在上传成功后执行了，代码如下：
`imged.save({
            onprogress:()=>console.log('fs')
        },(data)=>{console.log(data)})
            .then((data)=>this.setState({imgurl:data.attributes.url}));`

**Comment by leeyeh** [comment]
onprogress 会在上传的过程中多次被调用，如果文件比较小，很可能直接就 100% 了。

**Comment by 2016geek** [comment]
@leeyeh 我刚才调整了一下网速，上传还是没有执行，然后又换了一张7MB的图片，依然没有执行这个函数

**Comment by leeyeh** [comment]
我误解你的意思了，你试一下这段代码：

```javascript
imged.save({
  onprogress:function(){console.log('test');}
}, {}).then((data)=>this.setState({imgurl:data.attributes.url}));
```

**Comment by 2016geek** [comment]
@leeyeh 还是不行哈

**Comment by leeyeh** [comment]
找到原因了，稍后修复

**Comment by 2016geek** [comment]
@leeyeh 谢谢哈

**Comment by leeyeh** [comment]
http://jsplay.avosapps.com/hud/edit?js,console,output
