### ISSUE TITLE
移除 Backbone 风格的 callbacks 参数

### ISSUE THREAD

**Issue by leeyeh** [leancloud/javascript-sdk#357]
- [x] 将测试中使用 callbacks 参数的地方改成使用 Promise
  - [x] 引入 should.js，相比于 expect.js 提供了更好的 Promise 支持
- [x] 使用第三方 Promise 实现替换 AV.Promise
- [x] 删除代码中对 callbacks 的支持
- [x] 更新 API 文档
  - [x] 升级 jsdoc 至 v3（从 Realtime SDK 中复制相关的基础设施）

**Comment by wangxiao** [comment]
promise 为啥不试试官方出的这个版本？ https://www.npmjs.com/package/promise 

core-js 中的 Promise 有什么优势？

最好是和标准完全兼容的 promise lib，并且内部在浏览器支持 Promise 的情况下，能够使用原生 Promise。

**Comment by wangxiao** [comment]
貌似 https://github.com/stefanpenner/es6-promise 这个也是不错的选择
