### ISSUE TITLE
能否考虑增加一种初始化方式，只需要对代码做简单的修改

### ISSUE THREAD

**Issue by hhao** [leancloud/javascript-sdk#364]
初始化SDK时如果只提供APP_ID和分发签名的url（采用X-LC-Sign鉴权方式），
这样就可以将jssdk直接用于web页面，
也不会暴露APP_KEY，可以满足多种应用场景。

初始化代码类似下面这种：
var APP_ID = '...';
var SIGNATURE_URL = 'http://...';
AV.init({
  appId: APP_ID,
  sign_url: SIGNATURE_URL
});

**Comment by leeyeh** [comment]
相比于直接使用 appKey 在本地生成 signature，这没有更安全啊，我只需要用同样的 SIGNATURE_URL 来初始化，一样可以伪造成你的 app 来操作数据。

App Key 在设计中就是一个不可靠的鉴权方式，可以随便泄露，数据的安全需要通过 ACL 来保证。
