### ISSUE TITLE
JS SDK toJSON 方法丢失了 included 的字段内容

### ISSUE THREAD

**Issue by leeyeh** [leancloud/javascript-sdk#383]
https://forum.leancloud.cn/t/js-sdk-tojson-included/11564

**Comment by zhanziyang** [comment]
请问解决了吗？如果没解决，目前怎么做比较好？

**Comment by puny-d** [comment]
同求解决方案，希望能有一个方法能获得http传输过来的原始json数据，而不是序列化以后的数据

**Comment by leeyeh** [comment]
fixed in https://github.com/leancloud/javascript-sdk/releases/tag/v3.0.0-beta.0

**Comment by davycook** [comment]
请问3.0.0什么时候可以用到

**Comment by leeyeh** [comment]
已经发布了。

如果你使用的是 npm 的话，可以使用 `npm install leancloud-storage@next` 安装。

**Comment by alafata100** [comment]
conversation.createMessagesIterator返回的数据还不行啊
