### ISSUE TITLE
node.js 网络异常的情况下 file.save() 返回的错误undefined

### ISSUE THREAD

**Issue by mtaa** [leancloud/javascript-sdk#384]
参考的文档中的代码，正常上传没问题, 断开网络的情况下返回的错误undefined, 最好有提示。
https://leancloud.cn/docs/leanstorage_guide-js.html#从数据流构建文件

```
      var file = new AV.File(name, localFile);
      file.save().then(function(file) {
        // 文件保存成功
        console.log(file.url());
      }, function(error) {
        // 异常处理
        console.error(error); // undefined
      });
```

补充说明:
第一次使用leancloud-storage，
源码里跟到`request.js -> AVRequest -> getServerURLPromise`捕获到的异常仍然是undefined。

**Comment by leeyeh** [comment]
fixed in #407
