### ISSUE TITLE
AV.query会返回排序的字段

### ISSUE THREAD

**Issue by gzldx** [leancloud/javascript-sdk#413]
Test表
objectid, name, sort

－－－－－－－－－－－－－－－－－－－－－－－－－－
example:
let query = new AV.query('Test');
query.ascending('sort');
query.select('name');
return query.find.then((res) => {console.log(res);});

我这里指定了只获取name字段，但是经过排序操作后，连sort也一起查出来了，请问是bug还是我的操作问题？

**Comment by leeyeh** [comment]
@killme2008

http://jsplay.avosapps.com/jaj/edit?js,console

**Comment by killme2008** [comment]
hello ，这是mongodb 官方的行为，会将 sort 字段加入结果。

**Comment by gzldx** [comment]
@killme2008 知道了

**Comment by killme2008** [comment]
@gzldx 考虑到已有的用户可能会依赖这个行为，这个行为无法变更，抱歉。

**Comment by gzldx** [comment]
@killme2008 没事，后续如果可以实现的话，可以做下兼容
