### ISSUE TITLE
Push 参数没有文档说明

### ISSUE THREAD

**Issue by leeyeh** [leancloud/javascript-sdk#450]
需要在文档中为 push_data 增加到 API doc 的链接。

https://forum.leancloud.cn/t/typeerror-data-push-time-tojson-is-not-a-function/13277

可能更好的做法是兼容字符串类型的 time 字段。

**Comment by weakish** [comment]
> 需要在文档中为 push_data 增加到 API doc 的链接。

现在文档中已经提了「AV.Push 的更多使用信息参考 API 文档 AV.Push」

> 兼容字符串类型的 time 字段

只支持 `Date` 的话，一看类型就明了用法。而 `Date | string`，光看类型并不清楚用法
（string 是只支持 REST API 要求的特定格式的 UTC 时间戳还是同时支持其他格式（甚至伪自然语言））
