### ISSUE TITLE
调试的时候能不能打印请求

### ISSUE THREAD

**Issue by lzwjava** [leancloud/javascript-sdk#49]
像iOS和android里的curl日志。

**Comment by killme2008** [comment]
不准备增加，因为用户总可以通过浏览器调试工具看到请求和应答，我们不能做的更好。

**Comment by lzwjava** [comment]
浏览器好像只能看到一个 url 路径的请求和应答，不能看到内部的很多请求。
![qq20150209-3](https://cloud.githubusercontent.com/assets/5022872/6102389/894ed32a-b070-11e4-92cf-87d1e9fcfcd7.png)

实际上这个请求执行了不少东西，
![qq20150209-4](https://cloud.githubusercontent.com/assets/5022872/6102390/8979bf04-b070-11e4-8bec-24a2f350509e.png)

希望能打印这上面代码几处query.find() 的 请求和应答。调试起来就方便许多。

**Comment by lzwjava** [comment]
补充一下，我这个是用在云代码后端 node js里，不是浏览器前端用。

**Comment by sunchanglong** [comment]
借助 node-inspector 可以 跟踪 咱们 的云代码 执行步骤。
https://github.com/node-inspector/node-inspector/issues/341
但这里貌似是还没实现 network 这块

**Comment by lzwjava** [comment]
主要是设置一个 setDebugLogEnabled 的开关，在 save 和 find 这些 API 内部 统一的请求函数里打印下请求与应答，成本也不高。

**Comment by killme2008** [comment]
能看到，你自己认真看下吧， chrome 的这个功能如果都不能支持，那也太差了。


在 2015年2月9日 下午3:33，lzwjava <notifications@github.com>写道：

> 浏览器好像只能看到一个 url 路径的请求和应答，不能看到内部的很多请求。
> [image: qq20150209-3]
> <https://cloud.githubusercontent.com/assets/5022872/6102389/894ed32a-b070-11e4-92cf-87d1e9fcfcd7.png>
>
> 实际上这个请求执行了不少东西，
> [image: qq20150209-4]
> <https://cloud.githubusercontent.com/assets/5022872/6102390/8979bf04-b070-11e4-8bec-24a2f350509e.png>
>
> 希望能打印这上面代码几处query.find() 的 请求和应答。调试起来就方便许多。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leancloud/javascript-sdk/issues/49#issuecomment-73467802>
> .
>



-- 
庄晓丹
Email:        killme2008@gmail.com xzhuang@avos.com
Site:           http://fnil.net
Twitter:      @killme2008
