### ISSUE TITLE
3.0.0 版本出现无法登陆的问题

### ISSUE THREAD

**Issue by kumasento** [leancloud/javascript-sdk#490]
测试环境：React Native 0.44.0，iOS 8.0
调用`AV.User.logInWithMobilePhoneSmsCode`后，React Native报出异常：
```
JSON value '<null>' of type NSNull cannot be converted to NSString

Error: {
    message = "Entries must be arrays of the form [key: string, value: string], got: (\n    \"1da4014b-458d-53fe-f510-8ac49688a3a7\"\n)";
}
```
完整异常信息：
![image](https://user-images.githubusercontent.com/8768839/27409182-192448b2-56d8-11e7-80ce-623421567e98.png)

**Comment by leeyeh** [comment]
请问调用这个 API 时传的参数是什么样的呢？

**Comment by kumasento** [comment]
两个参数分别是18638670575和416903，谢谢

2017年6月22日 +0100 AM7:02 Lee Yeh <notifications@github.com>，写道：
