### ISSUE TITLE
Angular4 File upload, onprogress 報錯。

### ISSUE THREAD

**Issue by Manjiz** [leancloud/javascript-sdk#500]
``` js
file.save({
  onprogress (e) {
    // { loaded: 1234, total: 2468, percent: 50 }
  }
})
```

> Argument of type '{ onprogress(e: any): void; }' is not assignable to parameter of type 'AuthOptions'.
  Object literal may only specify known properties, and 'onprogress' does not exist in type 'AuthOptions'.

**Comment by leeyeh** [comment]
fixed by 2864a2d976120f011747116bc1157643572ebd59.
