### ISSUE TITLE
react native 使用follow方法添加关注时报错

### ISSUE THREAD

**Issue by pandas16** [leancloud/javascript-sdk#506]
依照官网的demo写的
this.currentUser.follow(friendID).then(function(){
        //关注成功
}, function(err){
        //关注失败
        console.dir(err);
});
报错:
undefined is not a function (evaluating '.default.currentUser.follow(friendID)')

**Comment by leeyeh** [comment]
从这个异常看，currentUser.follow 是 undefined，你能打印出 currentUser 看一下吗？

另外，SDK 的版本是多少？

**Comment by pandas16** [comment]
确实获取到了currentUser
我在使用follow之前加了一个判断：
    this.currentUser = Leancloud.User.currentAsync();
      if (this.currentUser) {
        console.log("获取登录用户:"+JSON.stringify(this.currentUser));
        this.addFriend();//在这个方法中使用的follow
      }else{
        console.log("没有登录用户");
      }
这是打印的结果:
获取登录用户:{"":43,"_state":1,"_result":{"username":"sds","email":"xxxxxx2@qq.com","emailVerified":false,"mobilePhoneNumber":"xxxx","mobile……}
之后出现错误：
undefined is not a function (evaluating 'this.currentUser.follow('5994f7865c497d0057d23688')')

版本是3.0.4
之前使用2.5.0出现同样错误

**Comment by leeyeh** [comment]
currentAsync() 是一个异步 API，返回一个 Promise，而不是 User。

**Comment by pandas16** [comment]
啊哦，原来是这样，我理解错了，不好意思~
