### ISSUE TITLE
未读消息数实现有问题

### ISSUE THREAD

**Issue by musicode** [leancloud/javascript-sdk#517]
会话实例有一个 `unreadMessagesCount` 属性，表示该会话有多少条未读消息。

在展示一个会话列表时，肯定需要展示最后一条消息，于是会到 `queryMessage` 方法，`limit` 传 1 取获取。

这时，如果再次获取会话列表，会话的 `unreadMessagesCount` 变为 0 了，但用户可能并没有进入会话，查看所有的未读消息。

我想了解的是，`unreadMessagesCount` 变为 0 是什么原因导致的，是 `queryMessage` 么

**Comment by leeyeh** [comment]
这看起来是 leancloud-realtime 相关的问题，如还有问题，麻烦移步对应的 repo 再提一下。或者使用我们的论坛、工单支持渠道。
