### ISSUE TITLE
Conversation lastMessage 属性一直是空的

### ISSUE THREAD

**Issue by musicode** [leancloud/javascript-sdk#518]
lastMessage 属性在什么情况下会有值呢？

**Comment by musicode** [comment]
@leeyeh 方便回答一下么，现在这个属性形同虚设，我是通过拉一条历史消息实现的，但经常报超时错误

![image](https://user-images.githubusercontent.com/2732303/31434182-4589a90e-ae41-11e7-8a47-e3069b303647.png)

**Comment by leeyeh** [comment]
这个异常是命令超时了 https://github.com/leancloud/js-realtime-sdk/issues/576

**Comment by musicode** [comment]
就算没超时，lastMessage 属性也没有值，我想问获取最后一条消息的最佳方式是什么呢
