### ISSUE TITLE
live-query模块在哪里获取？

### ISSUE THREAD

**Issue by git-lt** [leancloud/javascript-sdk#523]
https://leancloud.cn/docs/livequery-guide.html
实时数据同步 LiveQuery 开发指南 里页面写的是在 var AV = require('leancloud-storage/live-query');
 
这样获取不到

**Comment by leeyeh** [comment]
请问你是在什么平台上使用？

**Comment by git-lt** [comment]
Web平台

**Comment by git-lt** [comment]
@leayeh

**Comment by leeyeh** [comment]
那么我猜你是通过 npm 安装的 SDK，然后通过打包工具编译。

请确认 SDK 版本 > v3.0.0

如果还有问题，请详细描述一下「这样获取不到」的现象。

**Comment by git-lt** [comment]
@leeyeh 嗯嗯，升级了版本可以了，不过请在文档里更新一下，要3.x以上的版本才能获取到，1.x 和 2.x都不能这样导入，谢谢
