### ISSUE TITLE
Error 相关的改进

### ISSUE THREAD

**Issue by leeyeh** [leancloud/javascript-sdk#524]
#### 背景

在 #505 (v3.1.1) 中，我们在 Error 的 message 属性中加了一些额外的信息，帮助定位问题。导致了依赖 error.message 进行判断的逻辑出现了一些 [问题](https://leanticket.cn/tickets/14713)。

Node 也遇到了类似的问题，并在 v9 中增加了 `error.code <string>` 属性： https://nodejs.org/dist/latest-v9.x/docs/api/errors.html#errors_error_code
不再建议开发者对 error.message 进行判断。

#### 提议

1. （不确定要不要做）在 v3 中 revert #505，对 error.message 的改动发布到 v4
2. 由于我们已经有 `error.code <number>` 了，因此需要增加一个 `error.symbol`（不知道叫什么）的属性来作为 error 的唯一标识。
3. 在 leanengine-node-sdk 的 [异常处理](https://github.com/leancloud/leanengine-node-sdk/blob/master/lib/leanengine.js#L129-L132) 中，需要将 catch 到的 Error 中的属性尽可能完整的传给客户端。

@jysperm @sdjcw

**Comment by jysperm** [comment]
>由于我们已经有 error.code <number> 了，因此需要增加一个 error.symbol（不知道叫什么）的属性来作为 error 的唯一标识。

有了 code 为什么还要 symbol？是一个 code 会对应多个 symbol 么？

>在 leanengine-node-sdk 的 异常处理 中，需要尽可能的将 catch 到的 Error 中的属性尽可能完整的抛出来。

这个是发给客户端的，只发 message 我觉得没什么问题。

**Comment by leeyeh** [comment]
我们现在的 code 是数字，而且并没有什么规则，并不方便用户扩展使用。

以这个 ticket 为例，我希望能实现云函数中抛出的异常中的信息，在客户端都能拿到，包括 symbol 甚至其他用户自己定义的属性。而 message 我们不保证在这个过程中是不变的。

**Comment by jysperm** [comment]
但是不是有错误代码的常量嘛，既然已经有 code 了，我就觉得不要再加一个新的表示方法了

**Comment by sdjcw** [comment]
我很喜欢 http status code，虽然是数字，但是有范围，能通过第一位数字快速确认是客户端错误，或者是服务端错误，也能通过完整的数字确认具体问题。

我不建议 code 和 symbol 同时存在，感觉这是重复。

**Comment by jysperm** [comment]
现在的 code 并不是 http status code，但又很像 ... 不过这个没办法，所有 SDK 都这样

**Comment by leeyeh** [comment]
那么 1, 2 都不需要做了。

我在 #525 里增加了另一个特性，如果服务端/云函数返回的异常里除了 code 与 error 字段还有其他的字段，这些字段会成为 error 的属性。用户有需要的话可以通过这个机制传递自定义的一些异常信息。
