### ISSUE TITLE
未知接口一直报错，但其它接口调用正常？

### ISSUE THREAD

**Issue by git-lt** [leancloud/javascript-sdk#532]
![image](https://user-images.githubusercontent.com/8443758/34372378-2b8842bc-eb0f-11e7-90db-f873ad6c8a20.png)

![image](https://user-images.githubusercontent.com/8443758/34372469-e8c836fc-eb0f-11e7-98fe-7ec173bee78d.png)

**Comment by leeyeh** [comment]
这个请求是我们用来路由应用请求的，如果失败了不会影响应用的正常功能，但是这是不正常的。这个异常的意思是请求的 response 不安全（与证书有关），但是我目前没有复现这个问题。

**Comment by git-lt** [comment]
@leeyeh 谢谢解答，我试了一下是mac上的QQ浏览器会报错，换了chrome请求正常了

**Comment by leeyeh** [comment]
谢谢你的反馈。我们 SA 怀疑与我们使用的证书有关，已经在调查这个问题了。因为与具体的 SDK 无关，这里先关闭了，如果有问题请再反馈。
