### ISSUE TITLE
API 文档有误

### ISSUE THREAD

**Issue by nicecui** [leancloud/javascript-sdk#534]
https://leancloud.github.io/javascript-sdk/docs/AV.User.html#.signUpOrlogInWithAuthDataAndUnionId
![image](https://user-images.githubusercontent.com/10130959/36775302-8697f42c-1c9c-11e8-8142-abd4d2b786d8.png)

**Comment by leeyeh** [comment]
fixed via 20ddf0411a07d75cbf745ff03f949fce3823c8c1
