### ISSUE TITLE
storage.js d.ts 定义错误，410行 find(options?: AuthOptions): Promise; 其中的Object应为Object[]

### ISSUE THREAD

**Issue by Riuhou** [leancloud/javascript-sdk#546]
410行 find(options?: AuthOptions): Promise<Object>; 其中的Object应为Object[]

**Comment by leeyeh** [comment]
https://github.com/leancloud/javascript-sdk/commit/07403ddb61067559e2a07b128389ae37b941636b

已经修复了，我们很快会发布一个新的 fix release。

**Comment by leeyeh** [comment]
感谢反馈。
