### ISSUE TITLE
ReferenceError: Can't find variable: atob

### ISSUE THREAD

**Issue by cynicok** [leancloud/javascript-sdk#551]
React Native环境下，使用base64方式上传图片报错：
var file = new AV.File (response.fileName, {base64: response.data});
file.save ();

error：
'send ImageMessage error: ', { [ReferenceError: Can't find variable: atob]
  line: 90664,
  column: 43,
  sourceURL: 'http://192.168.7.168:8081/index.bundle?platform=ios&dev=true&minify=false' }

请问下React Native环境下，如何上传文件？

**Comment by cynicok** [comment]
不好意思，看了下论坛发现别人也有问了同样问题已经有答复。
现在采用new AV.File (name, {blob: {uri: response.uri}});方式上传成功。

**Comment by XiaoJianPeng** [comment]
嗯，就是这种方式上传的
