### ISSUE TITLE
ReferenceError: Blob is not defined | 在小程序中如何传入二进制数据保存成文件

### ISSUE THREAD

**Issue by upupming** [leancloud/javascript-sdk#552]
代码段：

```js
getPDFByHTML(html) {
    // 已经 promise 化的 request，参见 https://github.com/upupming/HITMers/blob/dev/client/utils/requests.js
    return request({
      url: 'https://url-to-pdf-api.herokuapp.com/api/render',
      method: 'POST',
      header: {
        'Content-Type': 'application/json'
      },
      data: {
        html
      }
    }).catch(errorHandler)
      .then(statusCodeChecker)
      .then(res => {
        // (1)
        return new AV.File('test.pdf', {base64: Base64.encode(res.data)}, res.header['Content-Type'])
          .save()
          .then(file => console.log(file.url()));
      });
  }
```

现在从 [url-to-pdf-api](https://github.com/alvarcarto/url-to-pdf-api#examples) 获取到了 pdf 的二进制数据，但是在(1) 处当我尝试将其转换为 Base64 并上传时，出现下面的错误：

```js
av-weapp-min.js? [sm]:27 Uncaught (in promise) ReferenceError: Blob is not defined
    at r (av-weapp-min.js? [sm]:27)
    at av-weapp-min.js? [sm]:21
    at E (av-weapp-min.js? [sm]:21)
    at C (av-weapp-min.js? [sm]:21)
    at av-weapp-min.js? [sm]:21
    at Function.u (av-weapp-min.js? [sm]:21)
    at WAService.js:4
    at WAService.js:4
```

截图：

![image](https://user-images.githubusercontent.com/24741764/47250578-fe62da00-d455-11e8-85d6-805916dba259.png)

注：微信并没有内置的 Base64 支持，我是使用的其他第三方库，测试是没有问题的。

**Comment by leeyeh** [comment]
确认小程序中缺少 Blob 与 FormData 的支持对 base64 构造的文件上传有问题。我们会用另一个方式修复这个 bug。

**Comment by leeyeh** [comment]
做了一些调研与测试，这个问题解决起来会比预想中要麻烦一些，需要在小程序中对 base64 使用一种[特殊的上传方式](https://developer.qiniu.com/kodo/kb/1326/how-to-upload-photos-to-seven-niuyun-base64-code)，这需要对 SDK 内部对 File 的处理做出一些结构上的调整。

如果着急的话，我建议在你部署的 url-to-pdf-api.herokuapp.com 中用 SDK 来上传文件。

**Comment by upupming** [comment]
还有一个问题想请教一下，目前发现使用 `curl -o` 命令可以直接生成 pdf：

```bash
$ curl -o html.pdf -XPOST -d'{"html": "<body>test</body>"}' -H"content-type: application/json" https://html-pdf-api.herokuapp.com/api/render
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16485  100 16456  100    29   3973      7  0:00:04  0:00:04 --:--:--  3980
```

但是在 Postman 或者小程序中调用 API 时返回的是一个字符串（内容相同），也不知道是何种格式编码的：

![image](https://user-images.githubusercontent.com/24741764/47282560-53e3e600-d612-11e8-8942-d9e018a79a48.png)

我尝试直接把这段字符串复制到 txt 文档并将其重命名为 `.pdf` 文件，打开之后内容却是空白的：

![image](https://user-images.githubusercontent.com/24741764/47282641-a02f2600-d612-11e8-9c09-58b79fa81d4e.png)

而使用 curl 生成的 pdf 是可以有内容的：

![image](https://user-images.githubusercontent.com/24741764/47282685-c5239900-d612-11e8-9d39-1dbbbf14fe19.png)

请问这是为什么呢？是这段字符串编码在传输过程中出问题了吗？我又该如何使用 leancloud 正确将这段字符串存储成想要的文件呢？

希望能够解答一下，先谢谢啦！

**Comment by upupming** [comment]
看了一下 [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data) 和[小程序文档](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html)原来是要将 `responseType` 设置成 `arraybuffer`。

然后我通过将 `Arraybuffer` 转换为 `Array`，后续还是会报错呀：

```js
    return request({
      url: 'https://html-pdf-api.herokuapp.com/api/render',
      method: 'POST',
      header: {
        'Content-Type': 'application/json'
      },
      responseType: 'arraybuffer',
      data: {
        html
      }
    }).catch(errorHandler)
      .then(statusCodeChecker)
      .then(res => {
        console.log(new Uint8Array(res.data));
        return new AV.File('test.pdf', new Array(new Uint8Array(res.data)))
          .save()
          .then(file => console.log(file.url()));
      });
```

```txt
av-weapp-min.js? [sm]:27 Uncaught (in promise) ReferenceError: Blob is not defined
    at r (av-weapp-min.js? [sm]:27)
    at av-weapp-min.js? [sm]:21
    at E (av-weapp-min.js? [sm]:21)
    at C (av-weapp-min.js? [sm]:21)
    at av-weapp-min.js? [sm]:21
    at Function.u (av-weapp-min.js? [sm]:21)
    at WAService.js:4
    at WAService.js:4
```

**Comment by leeyeh** [comment]
返回的结果是二进制，将其作为字符串解码后会是乱码。目前 LeanCloud 的 SDK 只支持在浏览器与 Node.js 中直接通过二进制构造
File 上传，在小程序上还不支持（因为上述的问题）。

Li Yiming <notifications@github.com> 于2018年10月22日周一 下午4:17写道：

**Comment by leeyeh** [comment]
因为小程序的运行环境没有 Blob，wx.request 也不支持发送带二进制（ArrayBuffer）的 FormData，所以目前只能用 qiniu
提供的 base64 上传接口来特殊处理。  

\--  
Sent with [Ray](https://helloray.io/)

**Comment by upupming** [comment]
Any updates?
