### ISSUE TITLE
你好，我在ReactNative环境下使用RN，出现了Cannot read property 'register' of undefined的问题

### ISSUE THREAD

**Issue by ChenTianSaber** [leancloud/javascript-sdk#555]
我使用的版本如下：
"dependencies": {
    "leancloud-realtime": "^4.2.1",
    "leancloud-storage": "^3.11.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
  },

经过查询论坛发这是RN的一个已知BUG，并且官方回复说会修复的
论坛地址如下：https://forum.leancloud.cn/t/react-native-livequery/17882/8
然后我再git的changelog上发现说3.11.0版本修复了RN上undefined的问题，可是我试了下依旧不行

所以我想请问，这个问题被修复了吗，是我使用的包不对吗？
如果没有修复的话，请问什么时候会修复呢？
有没有暂时的解决方案呢？

**Comment by leeyeh** [comment]
你好确认 3.11.0 已修复这个问题，你可以通过 [这个帖子](https://forum.leancloud.cn/t/react-native-livequery/17882/7?u=leeyeh) 里的项目验证升级之后问题消失。如果你确认你的问题依旧，请提供一下复现的方法，谢谢。

**Comment by leeyeh** [comment]
请问你是否是曾经使用 <3.11.0 的版本，发现问题之后「升级」倒 3.11.0 的呢？

**Comment by ChenTianSaber** [comment]
> 请问你是否是曾经使用 <3.11.0 的版本，发现问题之后「升级」倒 3.11.0 的呢？

是的，我曾经使用的是3.10.0，发现问题后我试过升级也试过吧node包删除然后重新install，都不行，我看了下我node包下面的leancloud-storage包下的package.json，确实是3.11.0，所以我不知道是我npm出了问题还是什么

您可以试试npm安装一下，看看安装完之后的版本是不是3.11.0的，试试看这个问题有没有被解决

**Comment by ChenTianSaber** [comment]
> 那应该是某个地方的缓存出问题了。
> 
> 你可以运行 `npm ls leancloud-storage` 来检查 npm 安装的版本。
> 
> 如果 npm 安装的版本是正确的，请再试试清空 react native packager 的缓存。 Normally `npm start --reset-cache` will do the work.

谢谢您，确实是缓存问题
