### ISSUE TITLE
数据存储 410错误

### ISSUE THREAD

**Issue by xCss** [leancloud/javascript-sdk#557]
[预览地址](http://nonconformist.me/rfid-on-rpi/)(`F12`控制台，刷新)：

``` js
localStorage.setItem('debug', 'leancloud*'); // 控制台输出
```

[![_20181225181424](https://user-images.githubusercontent.com/10877162/50420382-fcabfd00-0870-11e9-8a87-da6681f46957.png)](https://user-images.githubusercontent.com/10877162/50420382-fcabfd00-0870-11e9-8a87-da6681f46957.png)

cc#[124](https://github.com/xCss/Valine/issues/124)

**Comment by leeyeh** [comment]
410 是该节点发现没有找到这个 appid，所以重定向到了可能正确的节点。鉴于这个请求包含的 appid 是以 `appid9l` 开头的，有很大的可能性是配置 appid 的时候粘贴错了。

**Comment by xCss** [comment]
收到，感谢@leeyeh
