### ISSUE TITLE
ts 定义文件中 AV.Object.createWithoutData 重载版本的疑问

### ISSUE THREAD

**Issue by hustlzp** [leancloud/javascript-sdk#566]
目前 ts 定义中有一个 AV.Object.createWithoutData 的[重载版本](https://github.com/leancloud/javascript-sdk/blob/master/storage.d.ts#L288)：

```
static createWithoutData<T extends Object>(
    className: new (...args: any[]) => T,
    objectId: string
): T;
```

但目前测试无法生成 T 的实例，而是普通的 AV.Object:

```
class Work extends AV.Object {
}

let work = AV.Object.createWithoutData(Work, "5cbdd7aea3180b7832e07f44")

console.log(work instanceof AV.Object)  // true
console.log(work instanceof Work)  // false
```

查看[源码](https://github.com/leancloud/javascript-sdk/blob/master/src/object.js#L78)，貌似不支持这个用法。

不知是定义文件的问题，还是我哪个地方理解错误。

谢谢。

**Comment by leeyeh** [comment]
这样写没问题： https://codesandbox.io/embed/7250p32yqj

我猜有可能 Work 是通过 AV.Object.extend 得到的。
