### ISSUE TITLE
AV.Object的d.ts定义中缺少disableBeforeHook函数

### ISSUE THREAD

**Issue by weakish** [leancloud/javascript-sdk#570]
related ticket: 20753

**Comment by leeyeh** [comment]
https://github.com/leancloud/leanengine-node-sdk/blob/master/leanengine.d.ts#L44-L49

**Comment by weakish** [comment]
看 #385 好像 disableBeforeHook 挪到 js sdk 里了，在 leanengine-node-sdk 里也没搜到 disableBeforeHook 的定义。

**Comment by weakish** [comment]
20753 也提到查询的 select 函数类型提示缺失，需要调查一下。

**Comment by leeyeh** [comment]
8d798d37f1bbcace4f2f05647257d897f34e73bb 465389cea5e1f6dde34e106faec1f7c62e4e8401
