### ISSUE TITLE
npm ERR! notarget No matching version found for leancloud-realtime@^5.0.0-alpha.3

### ISSUE THREAD

**Issue by jljsj33** [leancloud/javascript-sdk#572]
![image](https://user-images.githubusercontent.com/6802825/61358385-c84f6b00-a8ac-11e9-825e-51cabf3bf1bd.png)

![image](https://user-images.githubusercontent.com/6802825/61359842-d488f780-a8af-11e9-9d31-edb66fa823a0.png)

**Comment by weakish** [comment]
npm 仓库有这个版本：<https://www.npmjs.com/package/leancloud-realtime/v/5.0.0-alpha.3>

你可以检查下 npm 源配置是否正常，网络是否畅通。

**Comment by jljsj33** [comment]
你确定在依赖包里能安装 next 版本？？？`npm i leancloud-realtime@next` 是可以的。。 @weakish 建议发个 `--tag=beta`
