### ISSUE TITLE
兼容 React Native 的 AsyncStorage 与 community

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/javascript-sdk#581]
AsyncStorage 在新版本被移到了 react-native-community/react-native-async-storage 下面。
AsyncStorage 与community 两个同时使用的时候会有冲突。

工单： https://leanticket.cn/tickets/21532

**Comment by leeyeh** [comment]
Supported in [v4.4.0](https://github.com/leancloud/javascript-sdk/blob/master/changelog.md#440-2020-03-17)
