### ISSUE TITLE
【bug】 AV.Query进行关系查询时，get方法能获取到无权限的对象

### ISSUE THREAD

**Issue by CaoMeiYouRen** [leancloud/javascript-sdk#587]
简易代码如下：

```js
(async () => {
    //当前用户未登陆，无ACL权限
    let query = new AV.Query('Todo')
    query.include('user');//user为Pointer类型，指向另一个设置了ACL权限的对象
    let obj = await query.get('xxxxxxxxx')//get的对象本身未设置ACL权限
    console.log(obj.toJSON())//会显示user的内容
})()
```

考虑到使用find、first都无法获取到user的内容，get的表现应该与之一致。

**Comment by weakish** [comment]
能看下应用的控制台 > 存储 > 设置 > 其他 > 查询 include 引入的 Pointer 类型数据时校验 ACL 权限，这个选项勾上了吗？

一般而言这个选项是默认勾上的。但是如果是比较古老的应用可能没有勾，或者是之前在控制台操作过，把这个勾去掉了。

如果没有勾上的话，会有你所说的权限问题。

**Comment by CaoMeiYouRen** [comment]
我

> 能看下应用的控制台 > 存储 > 设置 > 其他 > 查询 include 引入的 Pointer 类型数据时校验 ACL 权限，这个选项勾上了吗？
> 
> 一般而言这个选项是默认勾上的。但是如果是比较古老的应用可能没有勾，或者是之前在控制台操作过，把这个勾去掉了。
> 
> 如果没有勾上的话，会有你所说的权限问题。

我从来没有修改过该选项，刚刚检查了也是默认勾选的。
之所以认为是bug，是因为通过find和first都无法获取到Pointer的内容，但是get却可以，表现不一致

**Comment by weakish** [comment]
十分感谢报告问题。我们将尽快修复。

**Comment by weakish** [comment]
这个 bug 已经修复。
