### ISSUE TITLE
LiveQuery对class绑定的class，会无法推送订阅？

### ISSUE THREAD

**Issue by CaoMeiYouRen** [leancloud/javascript-sdk#589]
A项目下有个Class_A
B项目下有个Class_B
无论是把Class_A绑定到Class_B还是Class_B绑定到Class_A，若只订阅了Class_A，则对Class_B操作无法推送Class_A的变化。只有直接对Class_A操作才行。
有什么解决方法吗？

**Comment by leeyeh** [comment]
很抱歉回复晚了。在收到这个问题后我们内部经过了很大范围的讨论，结论是目前没有什么好的解决方法。在[将来)(https://github.com/leancloud/javascript-sdk/wiki/Roadmap)，SDK 会支持访问多个应用，届时这个问题也就不再存在了。

**Comment by CaoMeiYouRen** [comment]
> 很抱歉回复晚了。在收到这个问题后我们内部经过了很大范围的讨论，结论是目前没有什么好的解决方法。在[将来](https://github.com/leancloud/javascript-sdk/wiki/Roadmap)，SDK 会支持访问多个应用，届时这个问题也就不再存在了。

好的，谢谢。我之后还是手动整合下两个项目吧
