### ISSUE TITLE
建议修改 init 参数 serverURLs 为 serverURL

### ISSUE THREAD

**Issue by bruceCzK** [leancloud/javascript-sdk#596]
加了s第一反应会以为是个数组，不仔细看文档的话很容易搞错。

**Comment by weakish** [comment]
其实 serverURLs 最早是一个 object，可以指定各服务的地址，后来增加了对字符串类型的支持（各服务地址相同），可以参考它的[类型定义][ts]。我们正考虑加一个 serverURL 的 alias。

[ts]: https://github.com/leancloud/javascript-sdk/blob/master/storage.d.ts#L1227

**Comment by bruceCzK** [comment]
感谢回答。

**Comment by weakish** [comment]
[4.3.0] 中加了 serverURL

[4.3.0]: https://github.com/leancloud/javascript-sdk/releases/tag/v4.3.0
