### ISSUE TITLE
不支持多实例

### ISSUE THREAD

**Issue by hustcc** [leancloud/javascript-sdk#597]
AV.init 全局初始化 storage appId 和 appKey。执行两次 AV.init 报错。所以导致一个网页无法打开两个 leancloud 应用。

问题来来自接入 [clz](https://github.com/hustcc/clz) 的时候，因为已经网页已经存在 valine 评论了。

**Comment by weakish** [comment]
这个在 [路线图](https://github.com/leancloud/javascript-sdk/wiki/Roadmap#%E5%A4%9A%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81) 上
