### ISSUE TITLE
sdk中缺少用户反馈组件api

### ISSUE THREAD

**Issue by CaoMeiYouRen** [leancloud/javascript-sdk#598]
就是 https://api.leancloud.cn/1.1/feedback 这个接口。似乎只有rest api，能否考虑在sdk中集成？

**Comment by leeyeh** [comment]
可以通过 SDK 的 request API 来调用 API，用户反馈组件本身没有特别多需要抽象的概念：

```js
AV.request('/feedback')
```

**Comment by CaoMeiYouRen** [comment]
> 可以通过 SDK 的 request API 来调用 Rest API，用户反馈组件本身没有特别多需要抽象的概念：
> 
> ```js
> AV.request('/feedback')
> ```

了解。
