### ISSUE TITLE
IE中出现“Promise”未定义

### ISSUE THREAD

**Issue by xCss** [leancloud/javascript-sdk#599]
最开始出现`Object.assign`未定义：  
[![image.png](https://imgkr.cn-bj.ufileos.com/47e5d013-e0eb-400a-a5b0-f6279ef737df.png)](https://imgkr.cn-bj.ufileos.com/47e5d013-e0eb-400a-a5b0-f6279ef737df.png)

我写了`Object.assign`的`Pollify`：  
[![image.png](https://imgkr.cn-bj.ufileos.com/98b0452a-3840-4f43-b00a-2a8ca77f2307.png)](https://imgkr.cn-bj.ufileos.com/98b0452a-3840-4f43-b00a-2a8ca77f2307.png)

然后就会出现`Promise未定义`：  
[![image.png](https://imgkr.cn-bj.ufileos.com/cf236cd1-9103-4967-ab9b-15f65e4b9a79.png)](https://imgkr.cn-bj.ufileos.com/cf236cd1-9103-4967-ab9b-15f65e4b9a79.png)

``` json
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "blueimp-md5": "^2.8.0",
    "leancloud-storage": "^4.5.0"
```

```
系统环境：Windows 10  企业版 v1803  
IE ： v11.648.17134.0
UserAgent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
Node: v6.9.0
Npm: v3.10.8

```

[![IE版本](https://imgkr.cn-bj.ufileos.com/7a9ebee6-7fea-4962-a935-c1a27545a27c.png)](https://imgkr.cn-bj.ufileos.com/7a9ebee6-7fea-4962-a935-c1a27545a27c.png)

请问该怎么解决~

**Comment by weakish** [comment]
IE 11 不支持 Promise

如果必须支持 IE 11 的话，可以尝试 2.x 版本的 SDK

**Comment by leeyeh** [comment]
fixed in v4.5.1
