### ISSUE TITLE
上传文件 "line":935,"column":51003,"sourceURL":"index.android.bundle" 

### ISSUE THREAD

**Issue by ghyzx** [leancloud/javascript-sdk#600]
React Native Android 上传文件报错
{"line":935,"column":51003,"sourceURL":"index.android.bundle"}
请问这是什么情况？

附：同样的代码，iOS能正常上传
相关代码：
let file = new AV.File(imgInfo.filename, {blob: {uri: imgInfo.path}});
        file.metaData('width', imgInfo.width);
        file.metaData('height', imgInfo.height);
        file.save().then((res) => { }).catch((err) => { });

运行环境
"react": "16.9.0",
 "react-native": "0.61.5",
"leancloud-storage": "^4.2.0",

华为手机 Android 4.x
小米手机 Android 4.x    Android 7.0 
3部测试机均报相同错误，网络也都正常。

**Comment by leeyeh** [comment]
请打印一下 catch 到的 err 的 err.messge 看一下是什么？

**Comment by ghyzx** [comment]
@leeyeh   err的全部内容就是  {"line":935,"column":51003,"sourceURL":"index.android.bundle"}

**Comment by leeyeh** [comment]
那请问在 Chrome 调试模式下正常吗？或者你能看到报错的这一行是什么吗？

**Comment by ghyzx** [comment]
感谢跟进。
条件所限（华为手机太老 Android 4.1.2，连上USB时不能访问相机、相册，没有图片上传；小米手机无SIM卡不让USB安装和调试），
没法通过USB调试，只能打包apk文件，然后通过蒲公英安装到真机，连接USB，在Android Studio上看log。
log只看得到上文那一条信息；

**Comment by ghyzx** [comment]
@leeyeh  
leancloud-storage  4.3.0以后好像有重大变更， 什么时候方便更新一下文档，react-native 下安装后 运行有报错

**Comment by leeyeh** [comment]
最新版本的 SDK 更新了的 React Native 的安装方式： https://github.com/leancloud/javascript-sdk/releases/tag/v4.4.0 。 主要是因为原有的 AsyncStorage 已经被 deprecatd 了。

文档中安装部分还在更新，会很快发布。

**Comment by ghyzx** [comment]
"leancloud-storage": "^4.6.1",   还是有一样的问题，iOS ok，Android报错 {"line":972,"column":3955,"sourceURL":"index.android.bundle"}

**Comment by ghyzx** [comment]
找到原因了，关闭issue
