### ISSUE TITLE
react-native适配问题

### ISSUE THREAD

**Issue by huasxin** [leancloud/javascript-sdk#601]
react-native app leancloud-storage 从4.3版本升级到4.5版本后，启动时提示av-rn.js文件无法找到，查询文档得知，4.4以后的版本均不提供该文件。
请问：
        1、js版本是否以后均不提供av-rn.js文件；
        2、react-native app如想使用leancloud服务，是否只能使用4.3以下的版本。

**Comment by weakish** [comment]
新版的初始化方式有所变动，详见文档： https://leancloud.cn/docs/start.html#hash828638245
