### ISSUE TITLE
无法使用4.7版本的新方法

### ISSUE THREAD

**Issue by wonderjar** [leancloud/javascript-sdk#623]
Changelog里有4.7版本，我们正好需要新增加的两个方法。但是没有publish这个版本到NPM

<img width="941" alt="截屏2020-10-06下午11 54 15" src="https://user-images.githubusercontent.com/8806004/95226569-af273700-082f-11eb-8172-86017cf422c4.png">

https://www.npmjs.com/package/leancloud-storage?activeTab=versions

<img width="752" alt="截屏2020-10-06下午11 55 07" src="https://user-images.githubusercontent.com/8806004/95226577-b2222780-082f-11eb-9f8c-7aac8c20646a.png">

@leeyeh 这个版本能publish吗

**Comment by sdjdd** [comment]
@wonderjar 您好，[v4.7.0](https://www.npmjs.com/package/leancloud-storage/v/4.7.0) 已发布。
