### ISSUE TITLE
save Object 相关的 bug

### ISSUE THREAD

**Issue by david-ying-chan** [leancloud/javascript-sdk#627]
const a = new AV.Object('A');
const b = new AV.Object('B');

a.set('someAttr', 'before');
b.set('a', a);

a.set('someAttr', 'after');
await a.save();
// b.set('a', a);
await b.save();

我把开发中碰到的问题抽象成了上述代码，a 是和 b 关联的一个对象，结果最后 save b 的时候，会重新 save a，而且会用之前的值做 save？具体到上面的场景，会把 a 的 someAttr 重新保存成 'before'；如果解开那行注释，才会保存成 'after'。这个表现很诡异。

另外，每次我显示 save b 的时候，为什么还要去 save a 呢？这样是不是额外调用了一次 save API？如果我的对象里关联了多个其它 N 个对象，难道需要调用 N+1 次 API？

**Comment by sdjdd** [comment]
@david-ying-chan  您好，上述代码与您的描述并不相符。

> 最后 save b 的时候，会重新 save a

并不会重新 save a ，因为 `await a.save();` 后，a 就拥有了 `objectId` ，SDK 会把 a 当作 `Pointer` 处理，保存时不会携带数据。

> 如果解开那行注释，才会保存成 'after'。

即便不重新执行 `b.set('a', a);` ，SDK 也会把 a 当作 `Pointer` ，行为同上。

> 每次我显示 save b 的时候，为什么还要去 save a 呢？

您提供的代码是不会在保存 b 的同时保存 a 的。但如果之前没有执行 `await a.save();` ，SDK 会先保存 a ，再把 a 当作 `Pointer` ，行为依然同上。

> 如果我的对象里关联了多个其它 N 个对象，难道需要调用 N+1 次 API？

SDK 会使用 [批量操作](https://leancloud.cn/docs/leanstorage_guide-js.html#hash787692837) 来保存所有被关联且未保存的对象，然后再保存持有引用的对象，所以一共会调用 2 次 API 。但在计费方面：「每一个分别的保存或同步操作在计费时依然会被算作一次请求」。

**Comment by JohnSmith0602** [comment]
@sdjdd 你好，不好意思，我在项目里实际写了上述的测试代码，表现确实如你所说，没有问题。我又细致看了一下我之前的代码，是因为中间做了这么一步：

const a = new AV.Object('A');
const b = new AV.Object('B');
a.set('someAttr', 'before');
**const copyOfA = _.cloneDeep(a);**
b.set('a', copyOfA);

......

这样子就会出问题了。这样就没法追踪到关联关系了是吗？

**Comment by sdjdd** [comment]
@JohnSmith0602 是的，copyOfA 与 a 是两个不同的 Object 。

**Comment by david-ying-chan** [comment]
@JohnSmith0602 我在自己的项目代码里已经用 workaround 绕过去了，不过其实建议你们能做一下这个兼容，我最初的 a 其实是通过 await (new AV.Query('A')).get(id) 拿到的，所以我猜应该是有希望对比出这两个 object 实际上是有关联的？

我之所以会 cloneDeep 是专门有一个函数处理 object set parameters，我这个函数又不希望去改变入参，所以会一开始做 cloneDeep，我相信应该也有其他人会这么操作，然后就会造成现在这样的问题。实在是有点隐蔽...

谢谢你的解答。

**Comment by sdjdd** [comment]
> 我最初的 a 其实是通过 await (new AV.Query('A')).get(id) 拿到的，所以我猜应该是有希望对比出这两个 object 实际上是有关联的？

这样获取到的 a 和 deepClone 出来的 copyOfA 确实是有关联的 —— 它们的 `objectId` 相同，指向云端 Class A 中的同一行数据。

但存在多个指向同一行数据的 Object 存在时，它们之间并不会感知到彼此数据的修改。这并不是“不兼容”，即便在同一个客户端内实现了这个功能，也无法在多个客户端之间同步。

所以 a 和 copyOfA 在保存时只会使用自己当前的数据，如果您：
1. 以 a 为基础克隆出 copyOfA
2. 修改并保存 a
3. 保存 copyOfA

那么就会丢失对 a 的修改。
