### ISSUE TITLE
支持大文件上传

### ISSUE THREAD

**Issue by weakish** [leancloud/javascript-sdk#649]
目前 JS SDK 使用的直接 `POST https://upload.qiniup.com` 的方式，大于 1 G 的文件七牛会报错 413 Request Entity Too Large.

需要改用[分片上传][doc]以支持大文件上传。

[doc]: https://developer.qiniu.com/kodo/6364/multipartupload-interface

**Comment by qiuyi116** [comment]
其它 SDK 本来就是使用的「分片上传」所以没这个问题吗。

**Comment by sdjdd** [comment]
能确定具体多大的文件会 413 吗，小文件还是想用直接上传的方式。

**Comment by sdjdd** [comment]
> 其它 SDK 本来就是使用的「分片上传」所以没这个问题吗。

也有可能是用户没用其它 SDK 上传过超大文件 :bad:

**Comment by leeyeh** [comment]
Android iOS SDK 都是支持分片上传的。

qiniu 的 JS SDK 的文档里说其策略是「大于 4M 时可分块上传，小于 4M 时直传」。不过我觉得可以再大一点。

**Comment by weakish** [comment]
> 能确定具体多大的文件会 413 吗

大于 1 G 的文件
