### ISSUE TITLE
报错403

### ISSUE THREAD

**Issue by Fgaoxing** [leancloud/javascript-sdk#673]
@juvenn 我在使用SDK编写登陆程序的node.js部分，部署后有时候好使，有时候报错。检查了key和id都没问题，API是国际版默认的，服务器在香港
由于现在不报错了，所以没办法提供报错信息，但基本就是API报错403

**Comment by Fgaoxing** [comment]
@juvenn @killme2008 @hjiang @sparanoid

**Comment by sdjdd** [comment]
抱歉没有及时回复。

从你描述的现象判断，API 产生 403 错误并非由 SDK 引起。这个 issue 我就先关闭了，后续有具体的报错信息可以继续回复。
