### ISSUE TITLE
如果我只是想使用gulp，就一定要使用javascript-sdk 么？

### ISSUE THREAD

**Issue by zEmily** [leancloud/javascript-sdk#76]
你好，我想使用gulp来构建我的前端，但是发现在本地可以全局安装gulp后，运行gulp命令来使gulpfile.js里的东西运行。但是到了线上环境，我不知道该如何使用gulp命令，一路找到这里，说这里可以使用gulp。
但是我想知道我想使用gulp，就一定要使用javascript-sdk 么？
还有其他方式么？

**Comment by wangxiao** [comment]
请问你是 LeanCloud 的 JavaScript SDK 的用户么？

**Comment by wangxiao** [comment]
如果是说使用 Gulp 来构建 Web 项目的问题，可以查阅 Gulp 官方文档，或者 Yeoman 的自动化构建脚手架。

**Comment by zEmily** [comment]
好的，谢谢哈～
