### ISSUE TITLE
提供获取在线参数的API

### ISSUE THREAD

**Issue by lzwjava** [leancloud/javascript-sdk#79]
用户反馈。

**Comment by aisk** [comment]
在线参数指什么？

**Comment by lzwjava** [comment]
https://blog.leancloud.cn/567/

![image](https://cloud.githubusercontent.com/assets/5022872/9271048/59b60432-42a9-11e5-8699-16dee471b67b.png)

**Comment by aisk** [comment]
懂了，Python SDK 和 JS SDK 都可以支持一下。

**Comment by weakish** [comment]
已伴随统计功能下线
