### ISSUE TITLE
兼容 ReactNative 运行环境

### ISSUE THREAD

**Issue by aisk** [leancloud/javascript-sdk#81]
- [x] 模块引入机制出错，目前 SDK 在 node 环境下使用 `module._compile`，需要先用 fs 模块读取子模块源代码。需要修改为 node 环境也打包成一个大文件。
- [x] localStorage 目前机制检查是否有 require 相关函数，再进行 require。需要改为发现存在 localStorage 就跳过。
- [x] xmlhttprequest 目前机制检查是否有 require 相关函数，再进行 require。需要改为发现存在 xmlhttprequest 就跳过。
- [x] Add React Native AsyncStorage Support for User Session

**Comment by mydearxym** [comment]
请问这个实现了吗  有example吗？

**Comment by aisk** [comment]
还没 example，不过和直接在 ReactNative 上使用其他第三方模块的步骤一样，没什么特别需要注意的。

**Comment by killme2008** [comment]
0.5.2 已经发布 @mydearxym

**Comment by mydearxym** [comment]
@killme2008  非常感谢。

**Comment by aisk** [comment]
@mydearxym example 可以参考这篇博客：https://blog.leancloud.cn/3188/

**Comment by Hybrid-Force** [comment]
@aisk 虽然在那篇博客里面有一个简单的例子声称可以在react native环境中使用leancloud的js sdk，但是，实际上，由于没有对react native的async storage的适配，导致当前用户的localstorage缓存是没法用的。也就是说，实际上，js sdk在react native环境中是无法“正常”使用的，这和当初parse的js sdk遇到的问题是一样的。
这个问题已经在 issue #115 中指出。请问近期是否会有计划针对react native async storage进行适配？

**Comment by aisk** [comment]
@Hybrid-Force 这个有计划做，可能下周就会开始。如果还有其他 ReactNative 下遇到的问题，欢迎随时联系我。

**Comment by Hybrid-Force** [comment]
@aisk 多谢！

**Comment by ssssssssssss** [comment]
Any progress here?

**Comment by leeyeh** [comment]
Closed by #152
