### ISSUE TITLE
signUp注册账号处理的疑问

### ISSUE THREAD

**Issue by isayme** [leancloud/javascript-sdk#87]
[JavaScript文档](https://leancloud.cn/docs/api/javascript/symbols/AV.User.html#signUp)说`signUp`之后`AV.User.current()` 就可以正常返回, 假如现在是这样的场景:
> 注册之后要求验证邮箱, 未验证前是不可以登录的(当前API就是这样的);
> 但是现在因为`signUp`这边注册完`AV.User.current()` 检测会认为已经登录成功.

这种情况如何处理呢?

**Comment by killme2008** [comment]
嗯，这里是歧义的地方，如果你确实不希望注册用户默认登录，可以在注册后，强制调用一次 logout
