### ISSUE TITLE
IE9/8 无法正常工作

### ISSUE THREAD

**Issue by killme2008** [leancloud/javascript-sdk#9]
用户反馈

**Comment by wangxiao** [comment]
兼容老版本浏览器方案：
1、用户网站配置一个 HTTPS 证书，这样 HTTPS 请求 HTTPS 就可以兼容；
2、或者，让用户将服务部署在我们的网站上，确保服务是同域请求；
3、或者，用户自己部署的服务器直接请求我们的 RESTful API，用户服务器相当于一个代理；
